---
title: "Analysis of the human host response to Loa Loa infection"
authors: "Clemens Dierks, Pinkus Tober-Lau"
orcid: 0000-0002-4560-8939
email: clemens.dierks@charite.de 
date: last-modified 
format: 
    html:
        code-fold: true
        code-overflow: wrap
        code-tools: true
        graphics: yes
        toc: true
        toc-location: left-body
        toc-title: "Outline"
        html-math-method: katex

bibliography: references.bib
bibliographystyle: ieee
---
## Overview

In this script, we explore the plasma proteome of N = 475 *loa loa* infected 
patients (INF) and loa-negative (LN) controls. First, we present sex and age 
demographics of the study population and discuss the influence of eosinophils 
on the LN participants. Then, we import analysis results from differential 
expression analysis (DEA) conducted in the limma R package 
(see r/loa_analysis.Rmd). We contrasted LN vs INF as well as for different 
severity levels within the loa-infected patients: Patients with reported eye 
worm infection (EW), patients with measured loa microfilaria in the blood (MF) 
and with both (EWMF). Furthermore, we explore the associations between measured 
proteins and reported symptoms in LN and EW patients. 
Finally, we train machine learning models to distinguish 
LN from INF, MF and EW. An overview of the study design is given here 
@Veletzky2022. An extensive introduction into Loa loa infections (or loiasis) 
can be found here @Ramharter2024.

## Libraries

```{python}
# general imports
import os
import sys
os.chdir(r"c:\\Users\\cleme\\OneDrive - Charité - Universitätsmedizin Berlin\\Projects\\02_NTD_CHARITE\\NTD")
sys.path.append('src')
sys.path.append('org')
sys.path.append('src/py')
import warnings
warnings.filterwarnings('ignore')

# data manipulation
import pandas as pd
import numpy as np
from itertools import combinations, product

# plotting
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
from adjustText import adjust_text
from matplotlib.colors import to_hex



# ml & statistics
import joblib 
from statsmodels.stats.multitest import multipletests
from sklearn.base import clone
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from sklearn.feature_selection import mutual_info_classif, RFECV, SelectKBest, f_classif
from sklearn.impute import KNNImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_curve, roc_auc_score, confusion_matrix, precision_score, recall_score, f1_score, auc
from sklearn.model_selection import train_test_split, LeaveOneOut,StratifiedKFold, cross_validate, cross_val_predict
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from scikit_posthocs import posthoc_dunn
from scipy.stats import spearmanr, mannwhitneyu, kruskal,chi2_contingency, chisquare
from sklearn.svm import SVC
from sklearn.utils import resample

from scipy.integrate import trapezoid
from itables import show
RANDOM_STATE = 42





#
from sklearn.metrics import accuracy_score, , roc_auc_score
from sklearn.metrics import roc_curve, auc
```

## Functions

```{python}
def plot_volcano_limma(
    data_volcano, save_path=None, show_plot=True, 
    add_info="", xlabel = "coef", fc=0.1):

    # Plot Volcano plots based on limma outputs

    # Select features based on significance and FC
    regulated_features = data_volcano[
        (data_volcano["adj.P.Val"]< 0.05) & 
        ((data_volcano["logFC"] < -fc) | 
        (data_volcano["logFC"] > fc))
        ].index
    
    # Plotting
    fig, ax = plt.subplots(1,1, figsize=(5,5))
    ax.scatter(
        x=data_volcano.loc[
            (data_volcano[f"adj.P.Val"] >= 0.05), f"logFC"], 
        y=-np.log10(
            data_volcano.loc[
                (data_volcano[f"adj.P.Val"] >= 0.05), 
                f"adj.P.Val"]), c="k", alpha=0.5)
    ax.scatter(
        x=data_volcano.loc[regulated_features, f"logFC"], 
        y=-np.log10(
            data_volcano.loc[regulated_features, f"adj.P.Val"]), 
            c="#FF3131", alpha=0.99, edgecolor="gray")

    ax.set_xlabel(
        "$\\bf{Log_{2} FC}$", fontdict={"size":14})
    ax.set_ylabel(
        "$\\bf{-log_{10} (p_{adj.})}$", 
        fontdict={"size":14, "weight":"bold"})        

    ax.axhline(1.3, c="gray", ls="--")
    ax.axvline(fc, c="gray", ls="--")
    ax.axvline(-fc, c="gray", ls="--")
    ax.set_xlim([-0.5, 0.8])
    # ax.set_xlim([-0.5, 1.3])
    # ax.set_ylim([-0.5, 16])
    ax.set_ylim([-0.5, 4])
    ax.set_yticklabels(ax.get_yticklabels(), fontweight="bold", fontsize=9)
    ax.set_xticklabels(ax.get_xticklabels(), fontweight="bold", fontsize=9)
    plt.grid()
    plt.tight_layout()

    if save_path != None:
        plt.savefig(os.path.join(save_path, f'{add_info}.png'),dpi=400)
    if show_plot:
        plt.show()
    else:
        plt.close()

    
def select_topF_imp(model, th_expl_imp):
    # Select features based on cumulative feature importanc
    feat_imps = pd.Series(model.feature_importances_)
    feat_imps = feat_imps[feat_imps > 0]
    cum_sum = feat_imps.sort_values()[::-1].cumsum()
    cum_sum = cum_sum[cum_sum < th_expl_imp]
    feature_names = pd.Series(model.feature_names_in_)
    return feature_names.loc[cum_sum.index]

def select_topF_mutualinfo(X_train, y_train, th_exp_imp):
    mic = pd.DataFrame(
        {"MIC_abs":mutual_info_classif(
            X_train, y_train, random_state=RANDOM_STATE)}, 
        index=X_train.columns).sort_values(by="MIC_abs")[::-1]
    mic["MIC_perc"] = mic["MIC_abs"]/mic["MIC_abs"].sum()
    mic["MIC_cumsum"] = mic["MIC_perc"].cumsum()
    mic = mic[mic["MIC_cumsum"] < th_exp_imp]
    return mic.index
def plot_fc_diff(limma_x,limma_y, xlabel, ylabel, save_path):
    limma_x = limma_x.fillna("")
    limma_y = limma_y.fillna("")

    # check for common features
    common_idx = list(set(limma_x.index) & set(limma_y.index))
    limma_x = limma_x.loc[common_idx]
    limma_y = limma_y.loc[common_idx]
    fc_x = limma_x["logFC"]
    fc_y = limma_y["logFC"]
    p_x = -np.log10(limma_x["adj.P.Val"])
    p_y = -np.log10(limma_y["adj.P.Val"])

    diff = np.abs(p_x.copy().dropna().values,p_y.copy().values)
    diff = (pd.Series(MinMaxScaler().fit_transform(diff.reshape(-1, 1)).ravel()))
    s_rho, p = spearmanr(fc_x,fc_y)

    # collect annotation 
    texts = []

    signif_both = 0
    signif_MFEW = 0
    signif_EW = 0

    # return diff
    fig, ax = plt.subplots(1,1, figsize=(8,8))
    for i in range(len(fc_x)):
        p_x = limma_x.loc[common_idx[i], "adj.P.Val"]
        p_y = limma_y.loc[common_idx[i], "adj.P.Val"]
        if limma_x.loc[common_idx[i], "genes"] != "nan":
            label = limma_x.loc[common_idx[i], "genes"].split(" ")[0]
            if label.startswith("IGL") | label.startswith("IGK") | label.startswith("IGHV") | label.startswith("IGHG4"):
                label=""
        else:
            ""
        if (p_x < 0.05) & (p_y >= 0.05):
            ax.scatter(
                fc_x[i],fc_y[i], c="tab:green", 
                alpha=0.5, s=(diff[i]+0.2)*180, ec="k")
            texts.append(plt.text(
                    y = fc_y[i],
                    x = fc_x[i],
                    s= label))
            signif_EW +=1
        elif (p_x >= 0.05) & (p_y < 0.05):
            ax.scatter(
                fc_x[i],fc_y[i], c="tab:blue", 
                alpha=0.5, s=(diff[i]+0.2)*180, ec="k", )
            texts.append(plt.text(
                    y = fc_y[i],
                    x = fc_x[i],
                    s= label))
            signif_MFEW +=1
        elif (p_x < 0.05) & (p_y < 0.05):
            ax.scatter(
                fc_x[i],fc_y[i], c="tab:red", 
                alpha=0.5, s=(diff[i]+0.2)*180, ec="k")
            texts.append(plt.text(
                    y = fc_y[i],
                    x = fc_x[i],
                    s= label, fontdict={"weight":"bold"}))
            signif_both +=1
        else:    
            ax.scatter(
                fc_x[i],fc_y[i], c="gray", 
                alpha=0.5, s=(diff[i]+0.2)*180, ec="k")
    adjust_text(texts,
            # expand=(1.2, 2),
            arrowprops=dict(arrowstyle='-', color='k'),
            # only_move={'text':'y','text':'x'}
            )

    ax.scatter(
        [], [], c="tab:blue", label="Signif. in MF + EWMF vs LN", 
        s=100, alpha=.7, ec="k", lw=1)
    ax.scatter(
        [], [], c="tab:green", label="Signif. in EW vs LN", 
        s=100, alpha=.7, ec="k", lw=1)
    ax.scatter(
        [], [], c="tab:red",  label="$\\bf{Signif. \ in \ both}$", 
        s=100, alpha=.7, ec="k", lw=1)
    ax.axhline(0, c="gray", ls="--")
    ax.axvline(0, c="gray", ls="--")
    ax.plot([-1.5,1.5], [-1.5,1.5], ls="--", c="k")
    ax.set_xlim([-.4, 0.8])
    ax.set_ylim([-.4, 0.8])
    ax.set_xticklabels(ax.get_xticklabels(), fontdict={"weight":"bold"})
    ax.set_yticklabels(ax.get_yticklabels(), fontdict={"weight":"bold"})
    # Plot IGHG4 seperately to not skew the visualization
    ax.text(0.51, 0.82, "IGHG4 [x: 1.05, y: 0.28]", c="tab:blue")
    fig.supxlabel("logFC " + xlabel, fontweight="bold")
    fig.supylabel("logFC " + ylabel, fontweight="bold")
    ax.legend(loc="lower right")
    plt.tight_layout()
    plt.savefig(os.path.join(save_path, f"{xlabel}_{ylabel}.png"), dpi=400)

    print(signif_both, signif_MFEW, signif_EW)

def plot_roc(
    fpr_test_lst, tpr_test_lst, 
    colors, contrasts, 
    add_info, save_path, show_plot=False):
    fig, ax = plt.subplots(1,1, figsize=(5,5))
    for fpr_test, tpr_test, c, cs in zip(
        fpr_test_lst, tpr_test_lst, colors, contrasts):
        auroc_test = 1-trapezoid(fpr_test, tpr_test)
        ax.plot(
            fpr_test, tpr_test, c=c, alpha=1, lw=5, 
            label=f"AUROC Val.: {auroc_test:.2f} ({cs})")
    ax.plot([0,1], c="gray", ls="--")
    ax.grid()
    # Labels
    ax.set_xlabel('FPR (1 - Specificity)', weight="bold", fontsize=14)
    ax.set_ylabel('TPR (Sensitivity)', weight="bold", fontsize=14)
    ax.set_xticklabels(ax.get_xticklabels(), weight="bold")
    ax.set_yticklabels(ax.get_yticklabels(), weight="bold")
    plt.legend(ncols=1)
    plt.tight_layout()
    if save_path != None:
        plt.savefig(os.path.join(save_path, f"ROC{add_info}"), dpi=400)
    if show_plot:
        plt.show()
    else:
        plt.close()

def plot_cont_sympt(data, res_cont_dict, c, t, save_path, add_info=""):

            sympt_label = {
                'unspecific': 'Unspecific',
                'neurological': 'Neurological',
                'urticaria': 'Urticaria',
                'swelling_daily_life': 'Swelling',
                'myalgia_daily_life': 'Myalgia',
                'arthralgia_daily_life': 'Arthralgia',
                'pruritus_daily_life': 'Pruritus'}

            mapped_t = meta_table.loc[t, "Gene Names"].split(" ")[0]
            if mapped_t == "":
                mapped_t = t
            levels = [
                "LN asympt.", "LN sympt.",
                "EW asympt." ,"EW sympt.",
                "MF asympt.", "MF sympt."]
            x_labels = [
                "LN asympt.", "LN sympt.", 
                "EW asympt." ,"EW sympt.",
                "MF asympt.", "MF sympt."]
            colors = [
                (*colors_severity["LN"], 0.4),
                colors_severity["LN"],
                (*colors_severity["EW"], 0.4),
                colors_severity["EW"],
                (*colors_severity["MF"], 0.4),
                colors_severity["MF"],
                    ]
                
            df_plot = data[data[f"{c}_severity"].isin(levels)]
            fig , ax = plt.subplots(1,1, figsize=(5,4))
            sns.boxplot(
                data=df_plot, x=f"{c}_severity", y=t, order = levels,
                fliersize=0, palette=colors, fill=False)
            sns.stripplot(
                data=df_plot, x=f"{c}_severity", y=t, order = levels, 
                palette=colors, edgecolor="gray", linewidth=1, alpha=.2, s=4)
            ax.axvline(3.5, c="gray", lw=1, ls="--")
            ax.set_xticklabels(x_labels, fontdict={"weight":"bold"}, rotation=45)
            ax.set_xlabel(sympt_label[c],  fontdict={"weight":"bold"})
            ax.set_ylabel(
                "$\\mathbf{log_2}$ " + f"{mapped_t} abundance", 
                fontdict={"weight":"bold"})
            if add_info=="_jt_05":
                p = res_cont_dict[c].loc[
                    res_cont_dict[c].index==t, "JT_adj_pvalue"].values[0]
                ax.set_title(
                    f"{mapped_t}\n" + "$p_{jt}$: "+f"${p:.2f}$",
                            fontdict={"weight":"bold"})
            else:
                p = res_cont_dict[c].loc[
                    res_cont_dict[c].index==t, "KW_adj_pvalue"].values[0]
                ax.set_title(
                    f"{mapped_t}\n" + "$p_{kw}$: "+f"${p:.2f}$",
                            fontdict={"weight":"bold"})
            plt.grid()
            plt.tight_layout()
            plt.savefig(
                os.path.join(save_path, f"{c}_{mapped_t}{add_info}.png"),
                  dpi=300)
            # plt.show()
            plt.close()
def plot_loaMF_prot(df, x, y, target, order, colors, save_path=None, show_plot=False):
    # map uniprot -> gene symbol
    mapped_y = meta_table[meta_table.index == y]["Gene Names"].values[0]
        # remove NA's
    common_ids = list(set(df[x].dropna().index) & set(df[y].dropna().index))
    
    df = df.copy()
    df = df.loc[common_ids]

    # fit linear model for 
    m,b = np.polyfit(df.loc[:, x],df.loc[:, y],deg=1)
    fig, ax = plt.subplots(1,1, figsize=(3.5,3.5))
    ax.plot(df.loc[:, x], m*df.loc[:, x].values+b, lw=2, c="k", ls="--")
    sns.scatterplot(
        ax=ax, data=df, x=x, y=y, hue=target, alpha=0.8, 
        edgecolor="k", linewidth=1., legend=False, palette=colors,
        hue_order=order)
    ax.grid(alpha=0.5) 
    ax.set_ylabel("$\\bf{Log_2}$ Protein Abundance", fontdict={"weight":"bold"})
    ax.set_xlabel("$\\bf{Log_2}$" +  f" Loa mf / mL Blood", fontdict={"weight":"bold"})
    s_rho, p = spearmanr(df.loc[common_ids, x],df.loc[common_ids, y])
    ax.text(x=1, y=np.max(df[y])-.06, s=f"$y = {m:.2f}*x+{b:.2f}$" + "\ns$_{\\rho}$: " + f"{s_rho:.2f}, p: {p:.2f}")
    ax.set_title(mapped_y.split(" ")[0] + "\n", fontweight="bold")
    plt.tight_layout()
    if save_path != None:
        plt.savefig(os.path.join(save_path, f'{mapped_y}_{x}.png'),dpi=400)
    if show_plot:
        plt.show()
    else:
        plt.close()

def optimize_clf_with_loocv(
    X, y, clf, param_grid, random_state , scoring='roc_auc'):
    """
    Generic function to optimize any scikit-learn clf's hyperparameters using 
    Leave-One-Out Cross Validation (LOOCV).
    
    Parameters:
    - X: Feature matrix (numpy array or pandas DataFrame)
    - y: Target vector (numpy array or pandas Series)
    - clf: An instance of a scikit-learn classifier 
    (e.g., RandomForestClassifier, LogisticRegression, SVM etc.)
    - param_grid: A dictionary where keys are parameter names and values 
    are lists/ranges of values to try
    - random_state: Seed used for pseudo randomnes
    - scoring: The metric used for optimization ('roc_auc' by default). 
    an be any scikit-learn compatible metric.
   

    Returns:
    - best_params: Dictionary of the best parameters found
    - best_score: The best score (based on the specified scoring metric)
    - scores: obtained scores
    """
    
    # Initialize Leave-One-Out Cross-Validation
    loo = LeaveOneOut()
    best_score = -1  # Initialize best score
    best_params = None
    
    # Create a list of all combinations of hyperparameters
    param_names = list(param_grid.keys())
    # Cartesian product of all parameter values
    param_values = list(product(*param_grid.values()))
    param_index = list(
        product(*(range(len(values)) for values in param_grid.values())))

    scores = []
    # Iterate over all parameter combinations
    for i, (idx, param_set) in enumerate(zip(param_index, param_values)):
        param_dict = dict(zip(param_names, param_set))
        clf.set_params(**param_dict)  # Set clf parameters
        
        # adapt random state
        if "random_state" in clf.get_params():
            clf.set_params(**{"random_state":random_state})

        y_pred_prob = []
        y_preds = []
        y_true = []

        # LOOCV: Iterate over each train-test split
        for train_idx, test_idx in loo.split(X):
            X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
            y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
            y_true.append(y_test)
            # Train the clf on the current training set
            clf.fit(X_train, y_train)

            # Get predicted probabilities for clfs that support it
            try:
                y_pred_prob.append(clf.predict_proba(X_test)[:, -1])
            except AttributeError:
                # Fallback if clf doesn't support `predict_proba`
                y_pred_prob.append(clf.decision_function(X_test))
        
            y_preds.append(clf.predict(X_test))


        # Calculate AUROC for this fold   
        if scoring == 'roc_auc':
            score = roc_auc_score(y_true, y_pred_prob)
        # Use other scoring metrics (like accuracy, f1, etc.)
        else:
            if scoring == 'accuracy':
                score = accuracy_score(y_true, y_preds)
            else:
                raise ValueError(
                    f"Scoring method {scoring} is not supported yet.")
        
        # Update best parameters if current mean score is better
        if score > best_score:
            best_score = score
            best_params = param_dict

        # print(i, score, best_score, param_values[i])
        scores.append(score)
    print("Run Finished")
    return best_params, best_score, scores, param_values

```

## Data Import

We import two different datasets, an imputed one 
were proteins with a missing value ratio of 
>40% were removed and the remaining ones imported 
with knn consisting of n=242 proteins and a non-imputed dataset containing 
n=274 proteins.

Furthermore, we exclude pregnant women (n=8) from the analysis and participants
< 18 years, and selected only patients with loa monoinfection and healthy 
controls.


```{python}
data = pd.read_csv(
	os.path.join("data", "preprocessed", "Preprocess_20240821_DioGenes_withoutCalCur7ves_2_min1peptides_NOIMP_LOA_NoMV.csv"),
	index_col=0
)

data_imp = pd.read_csv(
	os.path.join("data", "preprocessed", 
    "Preprocess_20240821_DioGenes_withoutCalCur7ves_2_min1peptides_IMP_LOA_MV04.csv"),
	index_col=0
)

# read technical meta table
meta_table = pd.read_csv(
    "results/loaloa/tables/technical_meta_table.csv", index_col=0)
meta_table.loc["P06396-2", "Gene Names"] = "GSN-2"
meta_table.loc["P04217-2", "Gene Names"] = "A1BG-2"
meta_table.loc["A0A075B6Q5", "Gene Names"] = "IGHV3-64-2"
meta_table.loc["P01042-2", "Gene Names"] = "KNG1-2"
meta_table.loc["Q14624-2", "Gene Names"] = "ITIH4-2"
meta_table.loc["P23142-4", "Gene Names"] = "FBLN1-4"
meta_table["Gene Name"] = [f.split(" ")[0] for f in meta_table["Gene Names"]]


data_imp["infection"] = data["infection"]

# remove patients under 18 years old
data = data[(data["age"]>= 18) | data["age"].isna()]
data_imp = data_imp[(data_imp["age"]>= 18) | data_imp["age"].isna()]
# define age groups
data["age_imp"] = data["age"].fillna(200)
data_imp["age_imp"] = data_imp["age"].fillna(200)
data["age_group"] = pd.cut(
    data["age_imp"], bins=[18, 34, 60, 200], labels=["<34", ">34 & <60", ">60"])
data_imp["age_group"] = pd.cut(
    data_imp["age_imp"], bins=[18, 34, 60, 200], labels=["<34", ">34 & <60", ">60"])

# Rename Severity Level
severity_level_dict = {
    "eye worm+":"EW", 
    "eye worm + microfilaria":"EWMF",      
    "microfilaria+":"MF",
    "hyper microfilaria":"MF",
    "healthy":"LN",
    "mansonella": "MP"
    }
data["disease severity"] = data["disease severity"].replace(
    severity_level_dict
)
data_imp["disease severity"] = data_imp["disease severity"].replace(
    severity_level_dict
)

# Rename controls to loa
data["infection"] = data["infection"].replace(
    {"healthy controls":"LN", "loa":"INF"})
data_imp["infection"] = data_imp["infection"].replace(
    {"healthy controls":"LN", "loa":"INF"})


# add threshold for absolute eosionophil counts
data["eos_high"] = ["1" if x > 0.5 else "0" for x in data["eos_abs"]]

# Load information about pregnancy and exclude pregnant women
data_imp = data_imp.loc[data_imp["pregnancy"]!="pregnant"]
data= data.loc[data["pregnancy"]!="pregnant"]


# Select all co infections 
data_mans = data.copy()


# Exclude all co infections from the rest of the analysis
data = data[data["infection"].isin(["loa", "healthy controls"])]

```

# Analysis Loa
```{python}
pept_data = pd.read_table(os.path.join(
    "data", "preprocessing_boris", "NTD_min1peptides","NTD_min1peptides_PrecursorQuantity_reprep_normalized.tsv"
))

pept_data = pept_data.iloc[2:]
pept_data.columns = ["Precursor.Id", "Stripped.Sequence", "Protein.Group", "Genes"] + list(pept_data.columns)[4:] 
pept_data=pept_data.T

filenames = pept_data.index[4:]
multi_index = pd.MultiIndex.from_frame(pept_data.iloc[:4].T)
pept_data = pept_data.iloc[4:].reset_index(drop=True)
pept_data.columns = multi_index
pept_data.index = filenames
```

```{python}
#color coding fr severity classes
colors_severity = {
    "LN": sns.color_palette("colorblind")[0],
    "MF": sns.color_palette("colorblind")[1],
    "EWMF": sns.color_palette("colorblind")[2],
    "EW": sns.color_palette("colorblind")[4],
}
colors_infection = {
    "LN": sns.color_palette("colorblind")[0],
    "INF": sns.color_palette("colorblind")[3],
}
```


```{python}
# Select blood counts and clinical symptoms from meta data
clinical_symptoms = list(data.columns[53:83])
# relative blood counts are reported in %, abs. eos, lym, bas, neu in [x10^3 / µL], hb [mg/dl]
blood_counts = list(data.columns[42:54]) + ["NLR", "BLR", "ELR", "MLR"]
blood_counts.remove("pru_history")

data[clinical_symptoms] = data[clinical_symptoms].replace({9, np.nan})

# Calculate common full blood counts ratios, such as NLR, BLR, ELR, MLR 
data["NLR"] = data["neu_abs"]/data["lym_abs"]
data["BLR"] = data["bas_abs"]/data["lym_abs"]
data["ELR"] = data["eos_abs"]/data["lym_abs"]
data["MLR"] = data["mon_abs"]/data["lym_abs"]

# Calculate log2 loa mf count 
data["LLmf"].replace({0:np.nan}, inplace=True)
data["LLmf_log2"] = np.log2(data["LLmf"]+1)
```


For the symptom analysis, we define more meaniningfull categoried instead of 
individual symptoms.
```{python}
# Group symptoms
cs_dict = {
    "unspecific" : ["headache", "fatigue"],
    "neurological": ["paralysis", "paresthesia"],
    "urticaria": ["urticaria"]
}
for k in cs_dict.keys():
    data_temp = data.copy()
    data_temp = data_temp[cs_dict[k]].dropna(how="all").fillna(0)

    data.loc[data_temp.index, k] = np.where(data_temp.sum(axis=1)>0, 1, 0)

cs_dict_history = {
    "swelling_daily_life" : (
        ["swelling", "cs_history"], 
        ["sw_sleep", "sw_work", "cs_consultation", "cs_lastyear"]),
    "myalgia_daily_life": (
        ["mya_history"],
        ['mya_consultation', 'mya_sleep', 'mya_work', 
        'mya_psychologicaldistress']),
    "arthralgia_daily_life": (
        ['art_history'],
        ['art_consultation', 'art_sleep', 'art_work', 
        'art_psychologicaldistress',]),
    "pruritus_daily_life" : (
        ["pru_history"],
        ['pru_consultation', 'pru_distribution','pru_sleep','pru_work', 
        'pru_psychologicaldistress',]
    )
}
for k in cs_dict_history.keys():
    data_temp = data.copy()
    idx_0 = []
    idx_1 = []
    for asymp in cs_dict_history[k][0]:
        idx_0 += list(data_temp.loc[data_temp[asymp]==0, asymp].index)
    idx_0 = list(set(np.ravel(idx_0)))

    for symp in cs_dict_history[k][1]:
        idx_1 += list(data_temp.loc[data_temp[symp]==1, symp].index)
    
    data.loc[idx_0, k] = 0
    data.loc[idx_1, k] = 1

# Define combine labels for disease group and reported symptoms
for cs in list(cs_dict.keys()) + list(cs_dict_history.keys()):
    data[f"{cs}_severity"] = data["disease severity"]+"_"+data[cs].astype(str)
    data[f"{cs}_severity"].replace(
    {
        "EW_0.0": "EW asympt.",
        "EW_1.0": "EW sympt.",
        "EWMF_0.0": "EWMF sympt.",
        "EWMF_1.0": "EWMF sympt.",
        "MF_1.0": "MF sympt.",
        "MF_0.0": "MF asympt.",
        "LN_0.0": "LN asympt.",
        "LN_1.0": "LN sympt."
    }, inplace=True)
```


```{python}
# select uniprot ids for proteomic features
common_proteins = meta_table.index
common_proteins_imp = list(set(data_imp.columns) & set(meta_table.index))

# Update imputed columns
meta_cols = list(set(data.columns).difference(common_proteins_imp))
data_imp = data_imp.loc[data.index]

data_imp = pd.concat([data[meta_cols], data_imp[common_proteins_imp]], axis=1)
```


LN controls also show high levels of eosinophils,
we apply a threshold of absolute eosinophil counts of 500 per µL blood to 
exclude patients with potential undetected parasitic coinfections.
```{python}
fig, ax = plt.subplots(1,1)
sns.boxplot(data=data,
            y="eos_abs", 
            x="disease severity",
            order=["LN", "EW", "EWMF", "MF"],
            ax=ax, fill=False, hue="disease severity", fliersize=0, legend=False
            )
sns.stripplot(data=data,
            y="eos_abs", 
            x="disease severity",
            order=["LN", "EW", "EWMF", "MF"],
            ax=ax,hue="disease severity", alpha=0.5, linewidth=1, edgecolor="k"
            )
plt.ylim([0,10])
plt.ylabel("abs. eosinophil count")
plt.grid()
plt.legend(loc="upper left")
plt.savefig("results/loaloa/manuscript/supplement/loa_eos_count.png", dpi=200)
```


```{python}
# remove all controls with and absolute eosinophil count > 0.5 (n=99)
data = data.drop(
    data[(data["eos_high"] == "1") & (data["disease severity"] == "LN")].index)

# Export data 
data.to_csv("data/analysis/loa/loa_data_05.csv", index=False)
data_imp = data_imp.loc[data.index]
data_imp.to_csv("data/analysis/loa/loa_data_imp_05.csv", index=False)

data_imp["disease severity"] = data_imp["disease severity"].replace(
    {"HYMF":"MF"})
```


```{python}
# Create paths to store results
res_path_plots = "results/loaloa/plots"
res_path_tables = "results/loaloa/tables"
res_path_manuscript = "results/loaloa/manuscript"
```

## Age & Sex Distribution
We investigated age and sex distributions between LN and INF
in our dataset, since we know that a big fraction of the high abundant 
plasma proteome shows significant differences between sexes and age groups 
(@Dierks2024, @Dordevic2023).
Therefore, we explore age and sex differences between LN and INF, as well as 
between the different severity level.

```{python}
data_sex = data.copy()
data_sex["sex"] = data["sex"].replace({0:"Women", 1:"Men"})
fig, ax = plt.subplots(1,1)
sns.violinplot(ax=ax,
    data=data_sex, x="infection", y="age", hue="sex", split="sex",
    palette=["tab:blue", "tab:red"])
ax.grid()
ax.set_ylabel("age in years", fontweight="bold")
ax.set_xlabel("", fontweight="bold")
ax.set_xticklabels(ax.get_xticklabels(), fontweight="bold")
show(data_sex.groupby(["infection", "sex"])["age"].median())
```

Women in the LN group are 6 years younger than those in the INF 
group. Men in the LN group are about 4 years younger than in the INF group.

```{python}
data_sex = data.copy()
data_sex["sex"] = data["sex"].replace({0:"Women", 1:"Men"})
fig, ax = plt.subplots(1,1)
sns.violinplot(ax=ax,
    data=data_sex, x="disease severity", y="age", hue="sex", split="sex",
    palette=["tab:blue", "tab:red"], order=["LN", "MF", "EWMF", "EW"])
ax.grid()
ax.set_ylabel("age in years", fontweight="bold")
ax.set_xlabel("", fontweight="bold")
ax.set_xticklabels(ax.get_xticklabels(), fontweight="bold")
show(data_sex.groupby(["disease severity", "sex"])["age"].median())
```

When exploring age and sex distribution between the different severity levels, we find most prnounced differences within the the MF group (5.1 years). However, in the female EW subgroup, we find a bimodal age distribution. 

Due to missing or unclear age information for 41 participants in the LN group, 
we categorized age into three groups: under 34 years, between 34 and 60 years, 
and over 60 years. These age brackets were selected partly because we know that participants with missing age information are over 60 years old, and also based 
on findings from @Lehallier2019, which indicate that significant changes in the 
plasma proteome occur around the ages of 34 and 60.


```{python}
s = data.groupby(["infection"])["age_group"].value_counts(normalize=True).mul(100)
fig, ax = plt.subplots(1,1)
s.unstack(1).plot.bar( ax=ax,
    stacked=True, color=["#acd8a7", "#46923c", "#276221"], rot=0)
ax.set_xlabel("", fontweight="bold")
ax.set_xticklabels(ax.get_xticklabels(), fontweight="bold")
ax.set_ylabel("porportion in %", fontweight="bold")
plt.grid()
plt.tight_layout()
plt.show()
show(s)
```

The INF group is composed of less people under 40 (14%) compared to 
the LN group. The medium age group is well balanced.

```{python}
s = data.groupby(["disease severity"])["age_group"].value_counts(normalize=True).mul(100)
fig, ax = plt.subplots(1,1)
s.unstack(1).plot.bar( ax=ax,
    stacked=True, color=["#acd8a7", "#46923c", "#276221"], rot=0)
ax.set_xlabel("", fontweight="bold")
ax.set_xticklabels(ax.get_xticklabels(), fontweight="bold")
ax.set_ylabel("porportion in %", fontweight="bold")
plt.grid()
plt.tight_layout()
plt.show()
show(s)
```

When investigating the different severity groups the difference becomes even
more pronounced. While only having only 8.3 % of younger participants in the EWMF 
group, over 31 % in the LN group are younger than 40 years old. 

Now we check the sex distribution in the different severity groups:
```{python}
s = data_sex.groupby(["infection"])["sex"].value_counts(normalize=True).mul(100)
fig, ax = plt.subplots(1,1)
s.unstack(1).plot.bar( ax=ax,
    stacked=True, color=["tab:red", "tab:blue"], rot=0)
ax.set_xlabel("", fontweight="bold")
ax.set_xticklabels(ax.get_xticklabels(), fontweight="bold")
ax.set_ylabel("porportion in %", fontweight="bold")
plt.grid()
plt.tight_layout()
plt.show()
show(s)
```

Sex distributions between the INF and LN group are almost the same, with more women in both groups (~ 60%).

```{python}
s = data_sex.groupby(["disease severity"])["sex"].value_counts(normalize=True).mul(100)
fig, ax = plt.subplots(1,1)
s.unstack(1).plot.bar( ax=ax,
    stacked=True, color=["tab:blue", "tab:red"], rot=0)
ax.set_xlabel("", fontweight="bold")
ax.set_xticklabels(ax.get_xticklabels(), fontweight="bold")
ax.set_ylabel("porportion in %", fontweight="bold")
plt.grid()
plt.tight_layout()
plt.show()
show(s)
```

When investigating the different severity levels, we observed huge differences between the EW (27.7 % men) and MF (71.1 % men).

Furthermore, we are interested into the differences of sex in the different severity groups, 
since there are more male cases in the MF group and more female ones in EW.
```{python}
s = data_sex.groupby(["disease severity", "age_group"])["sex"].value_counts(normalize=False)
fig, ax = plt.subplots(1,1)
s.unstack(1).plot.bar( ax=ax,
    stacked=True, color=["#acd8a7", "#46923c", "#276221"], rot=0)
ax.set_xlabel("", fontweight="bold")
ax.set_xticklabels(ax.get_xticklabels(), fontweight="bold", rotation=60)
ax.set_ylabel("Count", fontweight="bold")
plt.grid()
plt.tight_layout()
plt.show()
show(s)
```
## Matching

Based on the observations in the previous section, we balance disease groups 
for age (groups). Code and documentation for 
matching can be found in the correspoding R-script in *src/R/loa_analysis.Rmd*.
## Differential Expression Analysis

Differential expression analysis was performed in R with the limma package.

```{python}
# load limma results and sort them as the first one
limma_inf_ctrl = pd.read_csv(
    "results/loaloa/tables/dea_limma/ln_infected_05.csv", 
    index_col=0)
limma_mfewmf_ctrl = pd.read_csv(
    "results/loaloa/tables/dea_limma/ln_mfewmf_05.csv", 
    index_col=0)
limma_mfewmf_ctrl["logFC"] = limma_mfewmf_ctrl["logFC"] *-1
limma_ew_ctrl = pd.read_csv(
    "results/loaloa/tables/dea_limma/ln_ew_05.csv", 
    index_col=0)
limma_mf_ew = pd.read_csv(
    "results/loaloa/tables/dea_limma/mf_ew_05.csv", 
    index_col=0).loc[limma_inf_ctrl.index]
limma_mf_ewmf = pd.read_csv(
    "results/loaloa/tables/dea_limma/mf_ewmf_05.csv", 
    index_col=0).loc[limma_inf_ctrl.index]
limma_ew_ewmf = pd.read_csv(
    "results/loaloa/tables/dea_limma/ew_ewmf_05.csv", 
    index_col=0).loc[limma_inf_ctrl.index]
limma_ew_ctrl = pd.read_csv(
    "results/loaloa/tables/dea_limma/ln_ew_05.csv", 
    index_col=0).loc[limma_inf_ctrl.index]
```

Detailed information about the differential expression analysis can be found
in the mansucript. In short, we found only 5 proteins differentially regulated
when contrasting LN and INF, including IGHG4, LCP1, ACTBL2, IGHG3 and IGLV9-49.

When comparing LN to MF + EWMF, we found 76 proteins to be differentially 
regulated. Within the contrast of LN vs EW, we found 26 proteins. Only IGHG4 and
ACTB were differentially expressed between EW and MF.

```{python}
save_path_limma = "results/loaloa/plots/limma"
plot_volcano_limma(
    limma_inf_ctrl, add_info="volcano_ctrl_inf_05",
    save_path=save_path_limma)
# plot_volcano_limma(
#     limma_mf_ew, add_info="volcano_mf_ew_05",
#     save_path=save_path_limma)
# plot_volcano_limma(
#     limma_mf_ewmf, add_info="volcano_mf_ewmf_05",
#     save_path=save_path_limma)
# limma_ew_ewmf["logFC"] = limma_ew_ewmf["logFC"]*-1# contrast was defined inversly
# plot_volcano_limma(
#     limma_ew_ewmf, add_info="volcano_ew_ewmf_05",
#     save_path=save_path_limma)
# plot_volcano_limma(
#     limma_mfewmf_ctrl, add_info="volcano_mfewmf_ctrl_05",
#     save_path=save_path_limma)
# plot_volcano_limma(
#     limma_ew_ctrl, add_info="volcano_ew_ctrl_05",
#     save_path=save_path_limma)
```


```{python}
# boxplots for most prominent marker for manuscript, a.o Fig 1C
protein_sel = [
    "P01861", "P01860", "P01871-2", "P07737", "P05543", "P00738", "P02766", 
    "P01880;P01880-2", "O43866", "P13796", "A0A075B6K6",
    "P20742", "P04278"]
s = "infection"

data_matched_ln_inf = pd.read_csv(
    "data/analysis/loa/matched/data_matched_inf_ln.csv")

for t in protein_sel:
    df = data_matched_ln_inf[data_matched_ln_inf["infection"].isin(["INF", "LN"])]
    levels = ["LN", "INF"]
    colors = ["tab:blue", "tab:red"]
    x_labels = ["LN", "INF"]
    fig, ax = plt.subplots(1,1, sharex=True, figsize=(2,3))
    sns.boxplot(ax=ax, order=levels,
        data=df, x=s, y=t, fliersize=0, fill=False, legend=False, palette=colors)
    sns.stripplot(ax=ax, order=levels,
        data=df, x=s, y=t,
        legend=False, edgecolor="k", alpha=0.6, linewidth=1, palette=colors)
    ax.set_xticklabels(x_labels, fontdict={"weight":"bold"})
    ax.set_yticklabels(ax.get_yticklabels(), fontdict={"weight":"bold"})
    ax.set_xlabel("")
    mapped_t = meta_table.loc[t, "Gene Names"].split(" ")[0]
    ax.set_ylabel(f"$log_2$ {mapped_t} abund.", fontdict={"weight":"bold"})
    ax.set_ylabel("")
    ax.set_title(f"{mapped_t}", fontdict={"weight":"bold"})
    ax.grid()
    plt.tight_layout()
    plt.savefig(os.path.join(save_path_limma, f"{mapped_t}.png"), dpi=400)
    plt.close()
```

Next, we compare the signal of the contrasts LN vs MF+EWMF and LN vs EW. 
(Fig. 1D)

```{python}
plot_fc_diff(
    limma_ew_ctrl,limma_mfewmf_ctrl,
    xlabel="EW vs LN",ylabel="MF + EWMF vs LN", save_path=save_path_limma)
```

## Correlation of Plasma proteins with FBC (& ratios) and Loa microfilarial count

We calculated spearman correlation coefficients between full blood counts, 
their ratios and the micorfilarial loa count, a.o. Fig 1E.

```{python}
# create path
# save_path_ll =  f"results\loaloa\plots\prot_log2_llmf"
# if not os.path.exists(save_path_bc):
#     os.mkdir(save_path_bc)

# Select only data with loa loa mf count > 0
data[f"LLmf_log2"] = np.log2(data[f"LLmf"]+1)
data_zero_ll = data[data["LLmf_log2"]>0]
corr_LLmf = pd.DataFrame(
    [spearmanr(
        data_zero_ll[p], data_zero_ll["LLmf"], 
        nan_policy="omit") for p in common_proteins],
    index=common_proteins).sort_values(by="statistic")
corr_LLmf["Genes"] = meta_table.loc[common_proteins, "Gene Names"]


order=["MF", "EWMF"]
colors=[
    colors_severity["MF"], 
    colors_severity["EWMF"], 
]
```

Fig 1E

```{python}
fig, ax = plt.subplots(1,5, figsize=(12.5, 3))

for i, p in enumerate([
    "P01860", "P01861", "P13796",
    "P60709", "P05543"]): 

    df = data
    y=p
    x="LLmf_log2"
    target="disease severity"

    mapped_y = meta_table[meta_table.index == y]["Gene Names"].values[0]
    # remove NA's
    common_ids = list(set(df[x].dropna().index) & set(df[y].dropna().index))
    df = df.copy()
    df = df.loc[common_ids]
    # fit linear model
    m,b = np.polyfit(df.loc[:, x],df.loc[:, y],deg=1)
    ax[i].plot(df.loc[:, x], m*df.loc[:, x].values+b, lw=2, c="k", ls="--")

    sns.scatterplot(
        ax=ax[i], data=df, x=x, y=y, hue=target, alpha=0.8, 
        edgecolor="k", linewidth=1., legend=False, palette=colors,
        hue_order=order)
    ax[i].set_ylabel("")
    ax[i].set_xlabel("")
    ax[i].set_yticklabels(ax[i].get_yticklabels(), fontweight="bold")
    ax[i].set_xticklabels(ax[i].get_xticklabels(), fontweight="bold")
    s_rho, p = spearmanr(df.loc[common_ids, x],df.loc[common_ids, y])
    
    if p >= 0.001:
        ax[i].set_title(r'$\mathbf{{{}}}$ {}'.format(mapped_y.split(" ")[0], "\n $s_{\\rho}$: " + f"{s_rho:.2f}, p: {p:.3f}"))
    else: 
        ax[i].set_title(r'$\mathbf{{{}}}$ {}'.format(mapped_y.split(" ")[0], "\n $s_{\\rho}$: " + f"{s_rho:.2f}, p < 0.001"))
    ax[i].grid()  
ax[0].set_ylabel("$\\mathbf{log_2}$ protein abundance", 
            fontweight="bold")
ax[2].set_xlabel("$\\mathbf{log_2}$ Loa mf / ml", 
         fontweight="bold")
plt.tight_layout()
plt.savefig(
    os.path.join(
        "results", "loaloa", "manuscript", "Fig1E.png"
    ), dpi=400
)
```

Plot Correlation Matrix for Proteins vs FBC

```{python}
bc_label_dict = {
    "wbc":"WBC (abs.)",
    "lym_abs": "Lymph. (abs.)",
    "lymperc": "Lymph. (%)",
    "neu_abs": "Neutro. (abs.)",
    "neuperc": "Neutro. (%)",
    "mon_abs": "Monocy. (abs.)",
    "monperc": "Monocy. (%)",
    "eos_abs": "Eos. (abs.)",
    "eosperc": "Eos. (%)",
    "bas_abs": "Bas. (abs.)",
    "basperc": "Bas. (%)",
    "NLR":"NLCR (-)",
    "MLR":"MLCR (-)",
    "ELR":"ELCR (-)",
    "BLR":"BLCR (-)",
    "hb": "Hb (abs.)",
}
```

```{python}
var = blood_counts
protein_labels = [x.split(" ")[0] for x in meta_table.loc[common_proteins, "Gene Names"]]
clinical_labels = [bc_label_dict[x] for x in var]

# get p-values for corelations
p_values_df = pd.DataFrame(
    index=clinical_labels, 
    columns=protein_labels)
corr_df = pd.DataFrame(
    index=clinical_labels, 
    columns=protein_labels)
for v in var:
    for  p, pl in zip(
    common_proteins, protein_labels
    ):
        p_values_df.loc[
            bc_label_dict[v],
            pl,
        ] = spearmanr(
            data[p],data[v],
            nan_policy="omit" 
        )[1]
        corr_df.loc[
            bc_label_dict[v],
            pl,
        ] = spearmanr(
            data[p],data[v],
            nan_policy="omit" 
        )[0]
# adj p_values with fdr benjamini-hochberg procedure
p_values_adj_df = pd.DataFrame(
    index=clinical_labels, 
    columns=protein_labels)
p_values_adj_df = pd.DataFrame(
    columns=protein_labels,
    index=clinical_labels)
for c in range(p_values_df.shape[0]):
    p_values = p_values_df.iloc[c,:].reset_index(drop=True)
    non_nan_idx = p_values.notna()
    _, corrected_p_values, _, _ = multipletests(p_values.loc[non_nan_idx], method='fdr_bh')
    p_values_adj_df.iloc[c, non_nan_idx.index] = corrected_p_values

# we drop all proteins from tthat do not have any significant correlations
prot_idx_keep = ((p_values_adj_df.T.reset_index(drop=True).T < 0.05).sum()).replace({0:np.nan}).dropna()
p_values_adj_df = p_values_adj_df.iloc[:, prot_idx_keep.index]


corr_matrix = data.loc[:, var + list(common_proteins)].corr(method="spearman")
corr_matrix = corr_matrix.loc[var, list(common_proteins)]
corr_matrix.columns = protein_labels
corr_matrix.index = clinical_labels
corr_matrix = corr_matrix.iloc[:, prot_idx_keep.index]
```

```{python}
g = sns.clustermap(
    data = corr_matrix, 
    cmap='vlag', fmt="", cbar=True,
    row_cluster=False,
    center=0, vmin=-.45, vmax=.45,
    linewidths=.01,
    figsize=(28,5),
    annot_kws={"ha":"center", "va":"center"}, 
    annot=(p_values_adj_df < 0.05).replace({True:"*", False:""}),
    cbar_pos=[0.15, 0.53, 0.01, 0.4],
    xticklabels=True, yticklabels=True
    )
for _, spine in g.ax_heatmap.spines.items():
    spine.set_visible(True)
g.ax_heatmap.set_xlabel("Proteins", fontweight='bold')
g.ax_heatmap.set_ylabel(
    "Clinical Variables", fontweight='bold')
cbar = g.ax_heatmap.collections[0].colorbar
cbar.set_label(
    "Spearman's $\\bf{\\rho}$", weight='bold')
plt.
plt.savefig(
    os.path.join(res_path_plots, "correlation_clinicalVariables", "heatmap_corr_prot_clinicalVar.png"),
    dpi=600
    )
```
## Symptom Association

We also invesitigated to what extent proteins were associated to self-reported 
symptoms. Furthermore, patients in the EW group reported a higher symptom
load than patients infected with microfilaria only. Consequently, we investigated
to waht extent proteins show distinct pattern for the group asymptomatic LN, 
symptomatic LN, asymptomatic EW and symptomatic EW.

```{python}
# Analysis was performed in R (differential_abundance_analysis.rmd)
# Loading results and cleaning up columns

fp_analysis = "results/loaloa/tables/sympt_stat_analysis_unadjForSexAndAge_05_newCat.xlsx"
clinical_cat = list(cs_dict.keys()) + list(cs_dict_history.keys())
res_cont_dict = {
    c:pd.read_excel(fp_analysis, sheet_name=c) for c in clinical_cat 
}
for c in res_cont_dict.keys():
    df = res_cont_dict[c]
    # reorder columns 
    df = df[[
        "Uniprot", "Genes", 
        "KW_statistic", "KW_p_value", "KW_adj_pvalue", 
        "JT_statistic", "JT_p_value", "JT_adj_pvalue",
        "median_ln_asympt", "median_ln_sympt", 
        "median_ew_asympt", "median_ew_sympt",
        "n_ln_asympt", "n_ln_sympt", "n_ew_asympt", "n_ew_sympt"
        ]]

    # check which symptoms and protiens have less than 10 samples in 
    # one of the groups and assign nan values
    idx_low_samples = (
        (
            df[["n_ln_asympt", "n_ln_sympt", "n_ew_asympt", "n_ew_sympt"]] < 10
            ).sum(axis=1) > 0
        )
    df.iloc[idx_low_samples, 2:12] = np.nan
    df["JT_adj_pvalue"] = np.nan
    df["KW_adj_pvalue"] = np.nan
    
    non_na_mask = ~np.isnan(df["KW_p_value"])
    if np.sum(non_na_mask) > 0:
    # perform bonferroni adjustment
        df.loc[non_na_mask, "JT_adj_pvalue"] = multipletests(df.loc[non_na_mask, "JT_p_value"], method="fdr_bh")[1]
        df.loc[non_na_mask, "KW_adj_pvalue"] = multipletests(df.loc[non_na_mask, "KW_p_value"], method="fdr_bh")[1]
    df = df.set_index("Uniprot")
    res_cont_dict[c] = df
```

```{python}
# calculate number of significant assocaitions 
n_signif_kw = [sum(res_cont_dict[c]["KW_adj_pvalue"] <= 0.05) for c in clinical_cat ]
n_signif_jt = [sum(res_cont_dict[c]["JT_adj_pvalue"] <= 0.05) for c in clinical_cat ]

```

```{python}
symptoms_label_dict = {
    'unspecific':"Unspecific",
    'neurological':"Neurological",
    'urticaria': "Urticaria",
    'swelling_daily_life': "Swelling",
    'myalgia_daily_life': "Myalgia",
    'arthralgia_daily_life': "Arthralgia",
    'pruritus_daily_life': "Pruritus",
    }
```

Fig 2A
```{python}
## Heatmap

# rows proteins
# cols symptoms
diff_df = pd.DataFrame()
signif_jt_df = pd.DataFrame()
signif_kw_df = pd.DataFrame()

signif_prot_jt = []
signif_prot_kw = []

# Iterate over symptoms
for s in res_cont_dict.keys():
    # select symptom
    df_sympt = res_cont_dict[s]
    # calculate difference
    diff =  df_sympt["median_ew_sympt"] - df_sympt["median_ln_asympt"]
    # check for significant proteins
    signif_jt = df_sympt["JT_adj_pvalue"] <= 0.05
    signif_kw = df_sympt["KW_adj_pvalue"] <= 0.05
    diff_df[s] = diff
    signif_jt_df[s] = signif_jt
    signif_kw_df[s] = signif_kw
    # if signif proteins were found add tehm to list
    if signif_jt.sum() >0:
        signif_prot_jt.append(df_sympt[df_sympt["JT_adj_pvalue"] <= 0.05].index)
    if signif_kw.sum() >0:
        signif_prot_kw.append(df_sympt[df_sympt["KW_adj_pvalue"] <= 0.05].index)
signif_prot_lst_jt = list(set(np.concatenate(signif_prot_jt)))
signif_prot_lst_kw = list(set(np.concatenate(signif_prot_kw)))

diff_df.columns = res_cont_dict.keys()
signif_jt_df.columns = res_cont_dict.keys()
signif_kw_df.columns = res_cont_dict.keys()
diff_df.index = df_sympt.index
signif_jt_df.index = df_sympt.index
signif_kw_df.index = df_sympt.index

diff_df = diff_df.loc[signif_prot_lst_jt]
signif_jt_df = signif_jt_df.loc[signif_prot_lst_jt]
signif_kw_df = signif_kw_df.loc[signif_prot_lst_kw]

diff_df = diff_df.T
signif_jt_df = signif_jt_df.T

g = sns.clustermap(
    diff_df.fillna(0), 
    center=0, vmin=-0.8, vmax=0.8, cmap="vlag", 
    col_cluster=True, row_cluster=False,
    dendrogram_ratio=0.05, linewidths=.5,
    cbar_pos=[0.0, 0.53, 0.01, 0.4],
    annot=signif_jt_df.replace({True:"*", False:""}),
    fmt="", annot_kws={"ha":"center", "va":"center", "size":25}, 
    figsize=(28,6),
    mask=diff_df.isna(),
    yticklabels=[symptoms_label_dict[c] for c in diff_df.index])
for _, spine in g.ax_heatmap.spines.items():
    spine.set_visible(True)
g.ax_heatmap.set_facecolor('gray')
g.ax_heatmap.set_xlabel("Associated Proteins", fontweight='bold', size=14)
yticklabels = []
for label in g.ax_heatmap.get_xticklabels():
    yticklabels.append(
        meta_table.loc[label.get_text(), "Gene Names"].split(" ")[0]
    )
g.ax_heatmap.set_xticklabels(yticklabels, fontsize=14, fontweight="bold")
g.ax_heatmap.set_yticklabels(g.ax_heatmap.get_yticklabels(), fontsize=14, fontweight="bold")
g.ax_heatmap.set_ylabel("Reported Symptoms" , fontweight='bold', size=14)
cbar = g.ax_heatmap.collections[0].colorbar
cbar.set_label('log2 FC \n(EW sympt vs LN asympt.)', weight='bold', size=14)
cbar.set_ticks([-0.8, -0.4, 0. , 0.4, 0.8])
plt
plt.savefig(
    os.path.join(res_path_plots, "symptoms", "continuum_ln_ew_trend_jt_05newCat.png"),
    dpi=600
    )
```

```{python}
path_res_stat_cont = os.path.join(
    res_path_tables, "sympt_stat_analysis_comb_unadj_05_newCat.xlsx"
)
with pd.ExcelWriter(path_res_stat_cont) as writer:
    for k in res_cont_dict.keys():
        sn = symptoms_label_dict[k]
        st = res_cont_dict[k]
        # st.set_index("Uniprot", inplace=True)
        st.to_excel(writer, sheet_name=sn, index=True)
```
Next, we plot boxplots for the different proteins.

Among others, Fig 2C
```{python}
path_cont_boxplots= os.path.join(res_path_plots, "symptoms/continuum_ln_mf_ew_05_newCAT")
data_mono = data[((data["infection"].isin(["INF", "LN"])) & (data["disease severity"].isin(["EW", "LN", "MF"])))]
for c in signif_jt_df.index:
    for t in signif_jt_df.columns:
        if signif_jt_df.loc[c, t]:
            plot_cont_sympt(
                data_mono, res_cont_dict, c, t, path_cont_boxplots, add_info="_jt_05")

# for c in signif_kw_df.T.index:
#     for t in signif_kw_df.T.columns:
#         if signif_kw_df.T.loc[c, t]:
#             plot_cont_sympt(
#                 data_mono, res_cont_dict, c, t, path_cont_boxplots, add_info="_kw_05")
```

Fig 2B

```{python}
import pandas as pd
import igraph as ig
import matplotlib.pyplot as plt
import random
import matplotlib.colors as mcolors


df = signif_jt_df.copy()
symptoms_label_dict_netw = {
'unspecific': 'Fatique\n Headaches',
 'neurological': 'Paresthesia \n Paralysis',
 'urticaria': 'Urticaria',
 'swelling_daily_life': 'Swelling',
 'myalgia_daily_life': 'Myalgia',
 'arthralgia_daily_life': 'Arthralgia',
 'pruritus_daily_life': 'Pruritus'}
df.index = [symptoms_label_dict_netw[x] for x in df.index]

# Initialize igraph Graph
g = ig.Graph()

# Add symptoms as nodes
g.add_vertices(df.index)

# Calculate node sizes (number of proteins associated with each symptom)
node_sizes = df.sum(axis=1).tolist()  # sum of True values per row (symptom)

# Add edges and calculate weights based on shared proteins between symptoms
edges = []
weights = []
edge_labels = []

colors = ["gray" for i in range(len(df.index))]


for i in range(len(df.index)):
    for j in range(i + 1, len(df.index)):
        symptom1 = df.index[i]
        symptom2 = df.index[j]
        proteins1 = df.loc[symptom1]
        proteins2 = df.loc[symptom2]
        
        # Count shared proteins (True in both symptoms)
        shared_proteins = (proteins1 & proteins2).sum()
        
        if shared_proteins > 0:
            edges.append((i, j))
            weights.append(shared_proteins)
            edge_labels.append(shared_proteins)  # Store the number of shared proteins


# Add edges to the graph
g.add_edges(edges)

# Set the edge weights
g.es['weight'] = weights
edges_sorted_by_weight = sorted(g.es, key=lambda e: e['weight'])
# Plot the graph using igraph's plot functionality
layout = g.layout("circle")  # force-directed layout
fig, ax = plt.subplots(figsize=(8, 8))

# Convert node sizes for visualization scaling
visual_node_sizes = [size *2.8 for size in node_sizes]

# Create a colormap (e.g., 'viridis' or 'coolwarm')
norm_edge = plt.Normalize(vmin=min(weights), vmax=max(weights))
cmap_edge = cm.ScalarMappable(norm=norm_edge, cmap='Reds')
edge_colors = [cmap_edge.to_rgba(weight) for weight in weights]

for i, edge in enumerate(edges_sorted_by_weight):
    source, target = edge.source, edge.target
    g.es[edge.index]["width"] = 15  # Adjust edge width based on weight


# visual styling
visual_style = {
    "vertex_size": visual_node_sizes,
    "vertex_color": colors,
    "vertex_label_size": 12,
    "vertex_frame_color": "black",
    "vertex_label_angle": [i*2*np.pi for i in np.linspace(0,1,len(visual_node_sizes))],
    "edge_color": edge_colors, 
    "layout": layout,
    "target": ax  # render the plot in matplotlib's figure
}

# plot graph
ig.plot(g, **visual_style)
cbar_edge = plt.colorbar(cmap_edge, ax=ax, orientation="horizontal")
cbar_edge.set_label('Number of Overlapping Proteins', fontweight="bold", fontsize=12)
cbar_edge.ax.set_xticklabels(labels=cbar_edge.ax.get_xticklabels(), weight='bold', size=12)

plt.tight_layout()
plt.savefig(os.path.join(res_path_plots, "symptoms", "graph_symptoms.png"), dpi=400)
plt.show()
```
## Machine Learning

### Balanced Groups

We balanced different severity/manifestation groups by age groups and sex with
R's matchit package.
```{python}
ids_ml_1 = pd.read_csv(
    "data/analysis/loa/matched/data_matched_inf_ln_05.csv")["Sample ID"]
ids_ml_2 = pd.read_csv(
    "data/analysis/loa/matched/data_matched_ew_ln_05.csv")["Sample ID"]
ids_ml_3 = pd.read_csv(
    "data/analysis/loa/matched/data_matched_mfewmf_ln_05.csv")["Sample ID"]

data_ml_1 = data_imp[data_imp["Sample ID"].isin(ids_ml_1)]
data_ml_2 = data_imp[data_imp["Sample ID"].isin(ids_ml_2)]
data_ml_3 = data_imp[data_imp["Sample ID"].isin(ids_ml_3)]
```


```{python}
# Select Features and Labels
X_1 = data_ml_1[common_proteins_imp]
X_2 = data_ml_2[common_proteins_imp]
X_3 = data_ml_3[common_proteins_imp]

# Encode Labels
y_1 = data_ml_1["infection"].replace({"LN":0, "INF":1})
y_2 = data_ml_2["disease severity"].replace({"LN":0, "EW":1})
y_3 = data_ml_3["disease severity"].replace({"LN":0, "EWMF":1, "MF":1})
```

### Feature Selection

We applied 3 different feature selection methods:
- cumulative feature importance up to 0.7
- mutual information
- cross-validated recursive feature elimination

```{python}
# perform feature selection with Random Forest
rf_1 = RandomForestClassifier(max_depth=2, random_state=RANDOM_STATE)
rf_2 = RandomForestClassifier(max_depth=2, random_state=RANDOM_STATE)
rf_3 = RandomForestClassifier(max_depth=2, random_state=RANDOM_STATE)

# Fit on discovery cohort
rf_1.fit(X_1, y_1)
rf_2.fit(X_2, y_2)
rf_3.fit(X_3, y_3)
```

```{python}
# Feature selection
th_expl_imp = 0.7

## TOP KK
top_feat_cumImp_1 = select_topF_imp(model=rf_1, th_expl_imp=th_expl_imp)
top_feat_cumImp_2 = select_topF_imp(model=rf_2, th_expl_imp=th_expl_imp)
top_feat_cumImp_3 = select_topF_imp(model=rf_3, th_expl_imp=th_expl_imp)

## Mutual Information clf
top_feat_mutInf_1 = select_topF_mutualinfo(X_1, y_1, th_exp_imp=th_expl_imp)
top_feat_mutInf_2 = select_topF_mutualinfo(X_2, y_2, th_exp_imp=th_expl_imp)
top_feat_mutInf_3 = select_topF_mutualinfo(X_3, y_3, th_exp_imp=th_expl_imp)

# Recursive Feature Elimination
sk = StratifiedKFold(n_splits=10, random_state=RANDOM_STATE, shuffle=True)
sel_1 = RFECV(rf_1, step=5, cv=sk, verbose=False, min_features_to_select=10).fit(X_1, y_1)
sel_2 = RFECV(rf_2, step=5, cv=sk, verbose=False, min_features_to_select=10).fit(X_2, y_2)
sel_3 = RFECV(rf_3, step=5, cv=sk, verbose=False, min_features_to_select=10).fit(X_3, y_3)

top_feat_rfe_1 = X_1.columns[sel_1.support_]
top_feat_rfe_2 = X_2.columns[sel_2.support_]
top_feat_rfe_3 = X_3.columns[sel_3.support_]
```

```{python}
ml_path_plots = "results/loaloa/plots/ML_05"
ml_path_tables = "results/loaloa/tables/ML_05"
```

First, we optimize the number of trees and node in the random forest - 
after that we perform Leave-One-Out-CV.

```{python}
features_1 = [top_feat_cumImp_1, top_feat_mutInf_1, top_feat_rfe_1]
features_2 = [top_feat_cumImp_2, top_feat_mutInf_2, top_feat_rfe_2]
features_3 = [top_feat_cumImp_3, top_feat_mutInf_3, top_feat_rfe_3]

best_scores_lst_1, best_params_lst_1, scores_lst_1 = [], [], []
best_scores_lst_2, best_params_lst_2, scores_lst_2 = [], [], []
best_scores_lst_3, best_params_lst_3, scores_lst_3 = [], [], []

clf = RandomForestClassifier()
param_grid = {
    'max_depth': [2,3],
    'n_estimators': list(range(1,101,10))
}
```

```{python}

for i in range(3): # Number of feature sets
    X_1_feat = X_1[features_1[i]]
    X_2_feat = X_2[features_2[i]]
    X_3_feat = X_3[features_3[i]]

    best_params_1, best_score_1, scores_1, param_values = optimize_clf_with_loocv(
    X_1_feat, y_1, clf, param_grid, random_state=RANDOM_STATE, scoring='roc_auc',
    )

    best_params_lst_1.append(best_params_1)
    best_scores_lst_1.append(best_score_1)
    scores_lst_1.append(scores_1)

    best_params_2, best_score_2, scores_2, param_values = optimize_clf_with_loocv(
    X_2_feat, y_2, clf, param_grid, random_state=RANDOM_STATE, scoring='roc_auc',
    )
    best_params_lst_2.append(best_params_2)
    best_scores_lst_2.append(best_score_2)
    scores_lst_2.append(scores_2)

    best_params_3, best_score_3, scores_3, param_values = optimize_clf_with_loocv(
    X_3_feat, y_3, clf, param_grid, random_state=RANDOM_STATE, scoring='roc_auc',
    )

    best_params_lst_3.append(best_params_3)
    best_scores_lst_3.append(best_score_3)
    scores_lst_3.append(scores_3)

# save models
joblib.dump(
    best_params_lst_1, os.path.join(
        ml_path_tables, "loocv_opt", f"best_params_ml_1.pkl"))
joblib.dump(
    best_params_lst_2, os.path.join(
        ml_path_tables, "loocv_opt", f"best_params_ml_2.pkl"))
joblib.dump(
    best_params_lst_3, os.path.join(
        ml_path_tables, "loocv_opt", f"best_params_ml_3.pkl"))
joblib.dump(
    best_scores_lst_1, os.path.join(
        ml_path_tables, "loocv_opt", f"best_scores_ml_1.pkl"))
joblib.dump(
    best_scores_lst_2, os.path.join(
        ml_path_tables, "loocv_opt", f"best_scores_ml_2.pkl"))
joblib.dump(
    best_scores_lst_3, os.path.join(
        ml_path_tables, "loocv_opt", f"best_scores_ml_3.pkl"))
```

```{python}
X_1_feat_ref = X_1[features_1[0]]
param_grid_1 = {
    'max_depth': [2,3],
    'n_estimators': list(range(1,100,1))
}


X_2_feat_ref = X_2[features_2[0]]
param_grid_2 = {
    'max_depth': [2,3],
    'n_estimators': list(range(1,100,1))
}

X_3_feat_ref = X_3[features_3[2]]
param_grid_3 = {
    'max_depth': [2,3],
    'n_estimators': list(range(1,100,1))
}
```

```{python}

best_params_ref_1, best_score_ref_1, scores_ref_1, param_values_ref_1 = optimize_clf_with_loocv(
X_1_feat_ref, y_1, clf, param_grid_1, random_state=RANDOM_STATE, scoring='roc_auc',
)


best_params_ref_2, best_score_ref_2, scores_ref_2, param_values_ref_2 = optimize_clf_with_loocv(
X_2_feat_ref, y_2, clf, param_grid_2, random_state=RANDOM_STATE, scoring='roc_auc',
)

best_params_ref_3, best_score_ref_3, scores_ref_3, param_values_ref_3 = optimize_clf_with_loocv(
X_3_feat_ref, y_3, clf, param_grid_3, random_state=RANDOM_STATE, scoring='roc_auc',
)
```


```{python}
# Conduct LOOCV:

def perform_loocv(
    X, y, clf, param_dict, random_state,):
    
    # Initialize Leave-One-Out Cross-Validation
    loo = LeaveOneOut()

    clf.set_params(**param_dict)  # Set clf parameters
    
    # adapt random state
    if "random_state" in clf.get_params():
        clf.set_params(**{"random_state":random_state})

    y_pred_prob = []
    y_preds = []
    y_true = []
    feature_importances = []

    # LOOCV: Iterate over each train-test split
    for train_idx, test_idx in loo.split(X):
        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
        y_true.append(y_test)
        # Train the clf on the current training set
        clf.fit(X_train, y_train)

        # Get predicted probabilities for clfs that support it
        try:
            y_pred_prob.append(float(clf.predict_proba(X_test)[:, -1]))
        except AttributeError:
            # Fallback if clf doesn't support `predict_proba`
            y_pred_prob.append(float(clf.decision_function(X_test)))
    
        y_preds.append(int(clf.predict(X_test)))
        feature_importances.append(clf.feature_importances_)
    return y_pred_prob, y_preds, feature_importances


best_params_ref_1 = {'max_depth': 3, 'n_estimators': 39}
best_params_ref_2 = {'max_depth': 3, 'n_estimators': 70}
best_params_ref_3 = {'max_depth': 3, 'n_estimators': 85}

y_pred_prob_1, y_preds_1, feat_imp_1 = perform_loocv(
    X_1_feat_ref, y_1, clf, best_params_ref_1, random_state=RANDOM_STATE
)
y_pred_prob_2, y_preds_2, feat_imp_2 = perform_loocv(
    X_2_feat_ref, y_2, clf, best_params_ref_2, random_state=RANDOM_STATE
)
y_pred_prob_3, y_preds_3, feat_imp_3 = perform_loocv(
    X_3_feat_ref, y_3, clf, best_params_ref_3, random_state=RANDOM_STATE
)
```

Store results ..

```{python}
pd.DataFrame({
    "Sample_ID": data.loc[y_1.index, "Sample ID"],
    "y_true":y_1,
    "y_pred":y_preds_1,
    "y_pred_prob":y_pred_prob_1
}).to_csv(os.path.join(ml_path_tables, "res_table_1.csv"))
pd.DataFrame({
    "Sample_ID": data.loc[y_2.index, "Sample ID"],
    "y_true":y_2,
    "y_pred":y_preds_2,
    "y_pred_prob":y_pred_prob_2
}).to_csv(os.path.join(ml_path_tables, "res_table_2.csv"))
pd.DataFrame({
    "Sample_ID": data.loc[y_3.index, "Sample ID"],
    "y_true":y_3,
    "y_pred":y_preds_3,
    "y_pred_prob":y_pred_prob_3
}).to_csv(os.path.join(ml_path_tables, "res_table_3.csv"))
```


```{python}
res_ml_1 = pd.read_csv(
    os.path.join(ml_path_tables, "res_table_1.csv"), index_col=0)
res_ml_2 = pd.read_csv(
    os.path.join(ml_path_tables, "res_table_2.csv"), index_col=0)
res_ml_3 = pd.read_csv(
    os.path.join(ml_path_tables, "res_table_3.csv"), index_col=0)

y_1, y_preds_1, y_pred_prob_1 = res_ml_1["y_true"], res_ml_1["y_pred"], res_ml_1["y_pred_prob"]
y_2, y_preds_2, y_pred_prob_2 = res_ml_2["y_true"], res_ml_2["y_pred"], res_ml_2["y_pred_prob"]
y_3, y_preds_3, y_pred_prob_3 = res_ml_3["y_true"], res_ml_3["y_pred"], res_ml_3["y_pred_prob"]
```

Calculate ROC Curves
```{python}
fpr_1, tpr_1, th_1 = roc_curve(y_1, y_pred_prob_1)
fpr_2, tpr_2, th_2 = roc_curve(y_2, y_pred_prob_2)
fpr_3, tpr_3, th_3 = roc_curve(y_3, y_pred_prob_3)
```

Recently, a loa parasite peptide was used to develop a ELISA based assay
to detect loa infection in MF positive patients \ref{Greene2024}. 
The authors report sensitivities of 0 (n=23), 29.4(n=17) and between 
84-100 % (n=76) for patients with a mf count of <1000 mf/ml, 1000-7999 mf/ml 
and >8000 mf/ml. 

Here, we evaluate our ML models for sensitivity and report 71.02 (n=69), 
78.95 (n=38) and 100 (n=19) % for the same groups.  

```{python}
data_ml_3["mf_bins"] = pd.cut(
    data_ml_3["LLmf"], 
    bins=[0, 1000, 8000, 50000], 
    labels=["<1000", "<8000", "<50000"])

idx_all = data_ml_3[data_ml_3["mf_bins"].notna()].index
idx_1k = data_ml_3[data_ml_3["mf_bins"]=="<1000"].index
idx_8k = data_ml_3[data_ml_3["mf_bins"]=="<8000"].index
idx_50k = data_ml_3[data_ml_3["mf_bins"]=="<50000"].index

idx_allmf = data_ml_3[data_ml_3["mf_bins"].notna()].index

tn, fp, fn, tp = confusion_matrix(y_3.loc[idx_all], pd.Series(y_preds_3, index=y_3.index).loc
[idx_all]).ravel()
sensitivity_all = tp / (tp + fn)

tn, fp, fn, tp = confusion_matrix(y_3.loc[idx_1k], pd.Series(y_preds_3, index=y_3.index).loc
[idx_1k]).ravel()
sensitivity_1k = tp / (tp + fn)

tn, fp, fn, tp = confusion_matrix(y_3.loc[idx_8k], pd.Series(y_preds_3, index=y_3.index).loc[idx_8k]).ravel()
sensitivity_8k = tp / (tp + fn)
```


```{python}
fig, ax = plt.subplots(1,1, figsize=(5,1))
sns.histplot(ax=ax,
    x=data_ml_3.loc[idx_allmf, "LLmf"],
    alpha=0.3, color=colors_severity["EWMF"], edgecolor="k", linewidth=1), 
ax.set_yticklabels(ax.get_yticklabels(), weight="bold")
ax.set_xticklabels([])
ax.set_xlabel("")
ax.set_ylabel("N Pats.", fontweight="bold", fontsize=14)
ax.set_xticks([])

ax.spines[['right', 'top', "bottom"]].set_visible(False)
plt.tight_layout()
plt.savefig(
    os.path.join(ml_path_plots, "ml3_pred_prob_llmf_histpats.png"), 
    dpi=400, transparent=True)
plt.show()

fig, ax = plt.subplots(1,1, figsize=(0.5,5))
sns.histplot(ax=ax,
    y=pd.Series(y_pred_prob_3, index=y_3.index).loc[idx_allmf],
    alpha=0.3, color=colors_severity["EWMF"], edgecolor="k", linewidth=1),
ax.set_yticklabels([])
ax.set_xticklabels([])
ax.set_xlabel("")
ax.set_ylabel("")
ax.set_xticks([])
ax.set_yticks([])

ax.spines[['right', 'top', "bottom", "left"]].set_visible(False)
plt.tight_layout()
plt.savefig(
    os.path.join(ml_path_plots, "ml3_pred_prob_llmf_histpredprob.png"), 
    dpi=400, transparent=True)
plt.show()

fig, ax = plt.subplots(1,1, figsize=(5,5))
data_ml_3["LLmf_log10"] = np.log10(data_ml_3["LLmf"])
ax.scatter(
    y=pd.Series(y_pred_prob_3, index=y_3.index).loc[idx_allmf],
    x=data_ml_3.loc[idx_allmf, "LLmf"],
    alpha=0.3, ec="k", lw=0.5, c=colors_severity["EWMF"])
ax.axhline(0.5, c="gray", ls="--", lw=2)
ax.axvline(1000, c="gray", ls="--", lw=2)
ax.axvline(8000, c="gray", ls="--", lw=2)
ax.set_ylabel("$\\bf{\widetilde{P}\ (y=MF+EWMF)}$", fontweight="bold", fontsize=14)
ax.set_ylabel("Pred. Prob. (MF+EWMF)", fontweight="bold", fontsize=14)
ax.set_xlabel("Loa MF count per ml", fontweight="bold", fontsize=14)
ax.set_xticklabels(ax.get_xticklabels(), weight="bold")
ax.set_yticklabels(ax.get_yticklabels(), weight="bold")
ax.grid()
# plt.legend(["Patient Sample"])
spearmanr(
    pd.Series(y_pred_prob_3, index=y_3.index).loc[idx_allmf],
    data_ml_3.loc[idx_allmf, "LLmf"])
plt.savefig(os.path.join(ml_path_plots, "ml3_pred_prob_llmf.png"), dpi=400)
plt.show()
```


Furthermore, we invesitage the sensitivity in the EW classifier.

```{python}
tn, fp, fn, tp = confusion_matrix(y_2, pd.Series(y_preds_2, index=y_2.index)).ravel()
sensitivity_ew = tp / (tp + fn)

idx_ew_rl_ly = data_ml_2[data_ml_2["rl_lastyear"]==1].index
tn, fp, fn, tp = confusion_matrix(y_2.loc[idx_ew_rl_ly], pd.Series(y_preds_2, index=y_2.index).loc[idx_ew_rl_ly]).ravel()
sensitivity_ew_rl_ly = tp / (tp + fn)
```

```{python}
colors_contrasts = [
    colors_infection["INF"],
    colors_severity["EW"],
    colors_severity["EWMF"]
]
contrasts = ["INF", "EW", "MF+EWMF"]

plot_roc(
    [fpr_1, fpr_2, fpr_3],
    [tpr_1, tpr_2, tpr_3],
    colors= colors_contrasts,
    contrasts = contrasts,
    save_path = ml_path_plots,
    add_info ="_onlyValidation",
    show_plot=True
)
```

```{python}
res_roc = pd.concat([
    pd.DataFrame(
        [th_1, th_2, th_3],
        index = [f"Threshold_{c}" for c in contrasts ]).T.reset_index(drop=True),
    pd.DataFrame(
        [tpr_1, tpr_2, tpr_3],
        index = [f"TPR_{c}" for c in contrasts ]).T.reset_index(drop=True),
    pd.DataFrame(
        [fpr_1, fpr_2, fpr_3],
        index = [f"FPR_pos_{c}" for c in contrasts ]).T.reset_index(drop=True),
    ], axis=1)
res_roc.to_csv(os.path.join(ml_path_tables, "results_roc.csv"))
```

```{python}
def plot_predicted_probability(
    y_labels, predict_prob, colors, 
    xticklabels, ylabel,
    save_path,
    show_plot=True):
    fig, ax = plt.subplots(1,1,figsize=(2.5,2.5))
    sns.boxplot(
        data = pd.DataFrame({
        "label":y_labels,
        "prob":predict_prob,}), 
        x="label", y="prob",
        fill = False, palette=colors,
        fliersize=0
    )
    sns.stripplot(data = pd.DataFrame({
        "label":y_labels,
        "prob":predict_prob,
    }), x="label", y="prob",
    palette=colors, alpha=0.3, edgecolor="k", linewidth=0.5,
    )
    ax.set_ylim([0.0, 1])
    
    # ax.set_yticklabels([0.0, 0.2, 0.4, 0.6, 0.8, 1], fontweight="bold")
    ax.set_ylabel(ylabel, fontweight="bold")
    ax.set_xticklabels(xticklabels, fontweight="bold")
    ax.set_xlabel("")
    plt.grid()
    plt.tight_layout()
    if save_path != None:
        plt.savefig(os.path.join(save_path, f'pred_prob{"vs".join(xticklabels)}.png'),dpi=400)
    if show_plot:
        plt.show()
    else:
        plt.close()


plot_predicted_probability(
    y_1, y_pred_prob_1,
    colors=[
        colors_infection["LN"], 
        colors_infection["INF"]],
    xticklabels=["LN", "INF."], ylabel="Pred. Prob. (INF)",
    save_path=ml_path_plots)
plot_predicted_probability(
    y_2, y_pred_prob_2, 
    colors=[
        colors_severity["LN"],
        colors_severity["EW"]],
    xticklabels=["LN", "EW"], ylabel="Pred. Prob. (EW)",
    save_path=ml_path_plots)
plot_predicted_probability(
    y_3, y_pred_prob_3, 
    colors=[
        colors_severity["LN"],
        colors_severity["EWMF"]],
    xticklabels=["LN", "MF+EWMF"], ylabel="Pred. Prob. (MF+EWMF)",
    save_path=ml_path_plots)
```

Plot Feature importance of Random Forest Models.

```{python}
feat_imp_df_1 = pd.DataFrame(
    feat_imp_1, 
    columns=meta_table.loc[X_1_feat_ref.columns, "Gene Names"])
feat_imp_df_2 = pd.DataFrame(
    feat_imp_2, 
    columns=meta_table.loc[X_2_feat_ref.columns, "Gene Names"])
feat_imp_df_3 = pd.DataFrame(
    feat_imp_3, 
    columns=meta_table.loc[X_3_feat_ref.columns, "Gene Names"])
```

```{python}
def plot_featimp(
    feat_imp, color, save_path, add_info, show_plot=True, topk=15
):  
    y_ticklabels = [x.split(" ")[0] for x in feat_imp.columns]
    feat_imp = feat_imp.loc[:, feat_imp.mean().sort_values().index[::-1]]

    feat_imp = feat_imp.iloc[:, :topk].melt()
    alphas = np.linspace(1, 0.2, len(feat_imp))
    fig, ax = plt.subplots(1,1,figsize=(2.5,2.5))

    bars = sns.barplot(ax=ax,
        data = feat_imp,
        x="value",
        y="Gene Names",
        orient="y", 
        color=color,
        saturation=0.9,
    )
    for i, bar in enumerate(bars.patches):
        bar.set_alpha(alphas[i])
    ax.set_yticklabels(y_ticklabels, fontweight="bold")
    ax.set_xticklabels(ax.get_xticklabels(), fontweight="bold")
    ax.set_ylabel("", fontweight="bold")
    ax.set_xlabel("Feat. Imp", fontweight="bold")
    plt.tight_layout()
    # if save_path != None:
    #     plt.savefig(os.path.join(save_path, f'feat_imp{add_info}.png'),dpi=400)
    plt.show()
    # if show_plot:
    #     plt.show()
    # else:
    #     plt.close()

plot_featimp(
    feat_imp_df_1, colors_infection["INF"], 
    save_path=ml_path_plots, add_info="LNvsINF")
plot_featimp(
    feat_imp_df_2.iloc[:, :15], colors_severity["EW"], 
    save_path=ml_path_plots, add_info="LNvsEW")
plot_featimp(
    feat_imp_df_3.iloc[:, :15], colors_severity["EWMF"], 
    save_path=ml_path_plots, add_info="LNvsMF+EWMF")
```


Next, we assessed how sensitive our ML models are with respect to detection
of L. Loa infection in different groups of microfilarial burden and eyeworm.
```{python}
data_ml_3["mf_bins"] = pd.cut(
    data_ml_3["LLmf"], 
    bins=[0, 1000, 8000, 50000], 
    labels=["<1000", "<8000", "<50000"])

idx_all = data_ml_3[data_ml_3["mf_bins"].notna()].index
idx_1k = data_ml_3[data_ml_3["mf_bins"]=="<1000"].index
idx_8k = data_ml_3[data_ml_3["mf_bins"]=="<8000"].index
idx_50k = data_ml_3[data_ml_3["mf_bins"]=="<50000"].index

idx_allmf = data_ml_3[data_ml_3["mf_bins"].notna()].index



tn, fp, fn, tp = confusion_matrix(
    y_3.loc[idx_all], pd.Series(y_preds_3, index=y_3.index).loc
[idx_all]).ravel()
sensitivity_all = tp / (tp + fn)

tn, fp, fn, tp = confusion_matrix(
    y_3.loc[idx_1k], pd.Series(y_preds_3, index=y_3.index).loc
[idx_1k]).ravel()
sensitivity_1k = tp / (tp + fn)

tn, fp, fn, tp = confusion_matrix(
    y_3.loc[idx_8k], pd.Series(y_preds_3, index=y_3.index).loc[idx_8k]).ravel()
sensitivity_8k = tp / (tp + fn)
tn, fp, fn, tp = confusion_matrix(
    y_3.loc[idx_50k], pd.Series(y_preds_3, index=y_3.index).loc[idx_50k]).ravel()
sensitivity_50k = tp / (tp + fn)
```

Figure 3B
```{python}

fig, ax = plt.subplots(1,1, figsize=(5,1))
sns.histplot(
    ax=ax,x=data_ml_3.loc[idx_allmf, "LLmf"],
    alpha=0.3, color=sns.color_palette("colorblind")[5], 
    edgecolor="k", linewidth=1),
ax.set_yticklabels(ax.get_yticklabels(), weight="bold")
ax.set_xticklabels([])
ax.set_xlabel("")
ax.set_ylabel("N Pats.", fontweight="bold", fontsize=14)
ax.set_xticks([])
ax.spines[['right', 'top', "bottom"]].set_visible(False)
plt.tight_layout()
plt.savefig(
    os.path.join(ml_path_plots, "ml3_pred_prob_llmf_histpats.png"), 
    dpi=400, transparent=True)
plt.show()
```

Plots for selected Marker shown in Figure 1C.

```{python}
order = ["LN", "EW", "EWMF", "MF"]
colors = [colors_severity[g] for g in order]
fig, axs = plt.subplots(2,2, figsize=(5, 5))
for i, (p, ax) in enumerate(zip(
    ["P01860", "P01861", "P13796", "P60709"], 
    axs.ravel())):  
    mapped_t = meta_table.loc[p, "Gene Names"].split(" ")[0]
    sns.boxplot(ax=ax,
        data=data, y=p, x="disease severity", order=order,
        fill=False, fliersize=0, palette=colors)
    sns.stripplot(ax=ax,
        data=data, y=p, x="disease severity", order=order,
        palette=colors, edgecolor="gray", linewidth=1, alpha=.2)
    ax.set_ylabel("")
    ax.set_xlabel("")
    ax.set_xticklabels(order, fontweight="bold")
    ax.set_yticklabels(ax.get_yticklabels(), fontweight="bold")
    ax.set_title(mapped_t, fontweight="bold")
    ax.grid()
fig.supylabel("$\\mathbf{log_2}$ protein abundance", 
            fontweight="bold")
plt.tight_layout()
plt.savefig(os.path.join(
    ml_path_plots, f"Fig1C.png"),
    dpi=400
)
plt.show()
```

Since IGHG4 is by far the most important feature to distinguish LN from MF+EWMF. 
We check sensitivity and auroc only for ths protein.

```{python}
fpr_3_igg4, tpr_3_igg4, th_3_igg4 = roc_curve(y_3, data_ml_3["P01861"])
roc_auc_score(y_3, data_ml_3["P01861"])

plot_roc(
    [fpr_3_igg4],
    [tpr_3_igg4],
    colors= ["tab:blue"],
    contrasts = ["LN vs MF+EWMF, IGG4"],
    save_path = ml_path_plots,
    add_info ="_onlyIGG4_ml3",
    show_plot=True
)

## save results
roc_igg4 = pd.DataFrame({
    "TH":th_3_igg4,
    "FPR":fpr_3_igg4, 
    "TPR":tpr_3_igg4, 
    "Youden_J": tpr_3_igg4-fpr_3_igg4
})

# highest youden's index at log2 protein abundance of 19.46 - J = 0.51
th_igg4 = roc_igg4.sort_values(by="Youden_J")["TH"].iloc[-1]
y_igg4 = [1 if x > th_igg4 else 0 for x in data_ml_3["P01861"]]

tn, fp, fn, tp = confusion_matrix(
    y_3, pd.Series(y_igg4, index=y_3.index)).ravel()
sensitivity_all_igg4 = tp / (tp + fn)
```

# Revision Loa

*Revision 1:*
We add correlations between age and sex as well as sex differences within the text to the Supplement.

```{python}
candidates = ["IGHG3", "IGHG4", "ACTBL2", "IGLV9-49", "LCP1 PLS2", "SHBG", "ACTB", "FETUB", "S100A9 CAGB CFAG MRP14", "PFN1"]

data_matched = data[data["Sample ID"].isin(ids_ml_1)]

for c in candidates:
    mapped_c = meta_table[meta_table["Gene Names"]==c].index[0]
    fig, axs = plt.subplots(1,2, figsize=(10,5), sharey=True)
    
    for s in ["LN", "INF"]:
        data_sev = data[data["infection"]==s].copy()
        data_matched_sev = data_matched[data_matched["infection"]==s].copy()

        s_rho, p = spearmanr(
            data_sev[mapped_c], 
            data_sev["age"], 
            nan_policy="omit")
        s_rho_matched, p_matched = spearmanr(
            data_matched_sev[mapped_c], 
            data_matched_sev["age"], 
            nan_policy="omit")
        
        data_fit = pd.concat(
                [data_sev[mapped_c], data_sev["age"]], axis=1).dropna()
        m, b = np.polyfit(x=data_fit[mapped_c], y=data_fit["age"], deg=1)
        y_fit = m*data_fit[mapped_c]+b

        data_fit_matched = pd.concat([
            data_matched_sev[mapped_c], data_matched_sev["age"]
        ], axis=1).dropna()
        m_matched, b_matched = np.polyfit(x=data_fit_matched[mapped_c], y=data_fit_matched["age"], deg=1)
        y_fit_matched = m_matched*data_fit_matched[mapped_c]+b_matched


        if c in ["IGHG4", "ACTBL2", "IGLV9-49"]:
            m, m_matched = m_matched, m
            b, b_matched = b_matched, b

            s_rho, s_rho_matched = s_rho_matched, s_rho
            p, p_matched = p_matched, p

            axs[1].plot(data_fit[mapped_c], y_fit, c=colors_infection[s])
            axs[0].plot(data_fit_matched[mapped_c], y_fit_matched, c=colors_infection[s])
        else:
            axs[0].plot(data_fit[mapped_c], y_fit, c=colors_infection[s])
            axs[1].plot(data_fit_matched[mapped_c], y_fit_matched, c=colors_infection[s])

        axs[0].scatter(
            x=data_sev[mapped_c], 
            y=data_sev["age"],
            label= f"{s}, r: {s_rho:.2f}, p: {p:.2f}",
            c=[colors_infection[s]])
        axs[1].scatter(
            x=data_matched_sev[mapped_c], 
            y=data_matched_sev["age"],
            label= f"{s}, r: {s_rho_matched:.2f}, p: {p_matched:.2f}",
            c=[colors_infection[s]])

        axs[0].set_title("Before Matching", fontweight="bold")
        axs[1].set_title("After Matching", fontweight="bold")
    
        axs[0].legend()
        axs[1].legend()

        fig.supylabel(
            "age in years", fontweight="bold")
        fig.supxlabel(
            "$\\bf{Log_2}$" + f" {c.split(' ')[0]} Protein Abundance", fontweight="bold")

    plt.tight_layout()
    plt.savefig(os.path.join(
        "results", "loaloa", "manuscript", "Supplement_Review_1", f"age_{c.split(' ')[0]}_cont.png"
    ))
    plt.show()

    # break

    
```


```{python}
for c in candidates:
    mapped_c = meta_table[meta_table["Gene Names"]==c].index[0]
    fig, axs = plt.subplots(1,2, figsize=(10,5), sharey=True)

    sns.stripplot(
        ax=axs[0],
        data=data,
        x="age_group",
        y=mapped_c,
        hue="infection",
        dodge=True,
        c="k", s=1,
        legend=False
    )
    sns.stripplot(
        ax=axs[1],
        data=data_matched,
        x="age_group",
        y=mapped_c,
        hue="infection",
        dodge=True,
        c="k", s=1,
        legend=False
    )

    if c in ["IGHG4", "ACTBL2", "IGLV9-49"]:
        data, data_matched = data_matched, data

    sns.boxplot(
        ax=axs[0],
        data=data,
        x="age_group",
        y=mapped_c,
        hue="infection",
        palette=[colors_infection["LN"], colors_infection["INF"]],
        fliersize=0
    )
    sns.boxplot(
        ax=axs[1],
        data=data_matched,
        x="age_group",
        y=mapped_c,
        hue="infection",
        palette=[colors_infection["LN"], colors_infection["INF"]],
        fliersize=0,
        legend=False
    )

    axs[0].set_title("Before Matching")
    axs[1].set_title("After Matching")
    
    for ax in axs:
        ax.set_xlabel("")
        ax.set_ylabel("")
    

    fig.supxlabel(
        "age groups in years", fontweight="bold")
    fig.supylabel(
        "$\\bf{Log_2}$" + f" {c.split(' ')[0]} Protein Abundance", fontweight="bold")
    
    plt.tight_layout()

    plt.savefig(os.path.join(
        "results", "loaloa", "manuscript", "Supplement_Review_1", f"agegroups_{c.split(' ')[0]}_cat.png"
    ))    
    plt.show()

    break
    
```

Differences in Sex 

```{python}
for c in candidates:
    mapped_c = meta_table[meta_table["Gene Names"]==c].index[0]
    fig, axs = plt.subplots(1,2, figsize=(10,5), sharey=True)

    sns.stripplot(
        ax=axs[0],
        data=data,
        x="sex",
        y=mapped_c,
        hue="infection",
        dodge=True,
        c="k", s=3,
        legend=False,
        hue_order=["LN", "INF"],
        palette=[colors_infection["LN"], colors_infection["INF"]]
    )
    sns.stripplot(
        ax=axs[1],
        data=data,
        x="sex",
        y=mapped_c,
        hue="infection",
        dodge=True,
        c="k", s=3,
        legend=False,
        hue_order=["LN", "INF"],
        palette=[colors_infection["LN"], colors_infection["INF"]]
    )

    # if c in ["IGHG4", "ACTBL2", "IGLV9-49"]:
    #     data, data_matched = data_matched, data

    sns.boxplot(
        ax=axs[0],
        data=data,
        x="sex",
        y=mapped_c,
        hue="infection",
        palette=[colors_infection["LN"], colors_infection["INF"]],
        hue_order=["LN", "INF"],
        fliersize=0
    )
    sns.boxplot(
        ax=axs[1],
        data=data_matched,
        x="sex",
        y=mapped_c,
        hue="infection",
        hue_order=["LN", "INF"],
        palette=[colors_infection["LN"], colors_infection["INF"]],
        fliersize=0,
    )
    for ax in axs:
        ax.set_xlabel("")
        ax.set_xticklabels(["Women", "Men"])
        ax.set_ylabel("")
        ax.legend(loc="upper right")
    
    axs[0].set_title("Before Matching", fontweight="bold")
    axs[1].set_title("After Matching", fontweight="bold")

    fig.supxlabel(
        "Sex", fontweight="bold")
    fig.supylabel(
        "$\\bf{Log_2}$" + f" {c.split(' ')[0]} Protein Abundance", fontweight="bold")
    


    plt.tight_layout()
    plt.savefig(os.path.join(
        "results", "loaloa", "manuscript", "Supplement_Review_1", f"sex_{c.split(' ')[0]}_cat.png"
    ))
    plt.show()

```

Sex differences in EW vs EWMF 

```{python}
ids_ew_ewmf = pd.read_csv(
    "data/analysis/loa/matched/data_matched_ew_ewmf_05.csv")["Sample ID"]


data_matched = data_imp[data_imp["Sample ID"].isin(ids_ew_ewmf)]

```

```{python}
data_matched

for c in candidates:
    mapped_c = meta_table[meta_table["Gene Names"]==c].index[0]
    fig, axs = plt.subplots(1,2, figsize=(10,5), sharey=True)

    sns.stripplot(
        ax=axs[0],
        data=data,
        x="sex",
        y=mapped_c,
        hue="infection",
        dodge=True,
        c="k", s=3,
        legend=False
    )
    sns.stripplot(
        ax=axs[1],
        data=data_matched,
        x="sex",
        y=mapped_c,
        hue="infection",
        dodge=True,
        c="k", s=3,
        legend=False
    )

    # if c in ["IGHG4", "ACTBL2", "IGLV9-49"]:
    #     data, data_matched = data_matched, data

    sns.boxplot(
        ax=axs[0],
        data=data,
        x="sex",
        y=mapped_c,
        hue="infection",
        palette=[colors_infection["LN"], colors_infection["INF"]],
        fliersize=0
    )
    sns.boxplot(
        ax=axs[1],
        data=data_matched,
        x="sex",
        y=mapped_c,
        hue="infection",
        palette=[colors_infection["LN"], colors_infection["INF"]],
        fliersize=0,
    )
    for ax in axs:
        ax.set_xlabel("")
        ax.set_xticklabels(["Women", "Men"])
        ax.set_ylabel("")
        ax.legend(loc="upper right")
    
    axs[0].set_title("Before Matching", fontweight="bold")
    axs[1].set_title("After Matching", fontweight="bold")

    fig.supxlabel(
        "Sex", fontweight="bold")
    fig.supylabel(
        "$\\bf{Log_2}$" + f" {c.split(' ')[0]} Protein Abundance", fontweight="bold")
    


    plt.tight_layout()
    plt.savefig(os.path.join(
        "results", "loaloa", "manuscript", "Supplement_Review_1", f"sex_{c.split(' ')[0]}_cat.png"
    ))
    plt.show()
```

We further investigate for whether Sex differences between severity groups are statically significant. 
```{python}


# over all groups
contingency_table_all = pd.crosstab(data['sex'], data['disease severity'])
chi2, p_all, dof, expected = chi2_contingency(contingency_table_all)

# Infection
sex_counts_inf = data.loc[
    data["infection"]=="INF", 'sex'].value_counts().values
chi2, p_inf= chisquare(sex_counts_inf)

# EW
sex_counts_ew = data.loc[
    data["disease severity"]=="EW", 'sex'].value_counts().values
chi2, p_ew= chisquare(sex_counts_ew)

# MF
sex_counts_mf = data.loc[
    data["disease severity"]=="MF", 'sex'].value_counts().values
chi2, p_mf= chisquare(sex_counts_mf)

# EWMF
sex_counts_ewmf = data.loc[
    data["disease severity"]=="EWMF", 'sex'].value_counts().values
chi2, p_ewmf= chisquare(sex_counts_ewmf)
```


```{python}
mannwhitneyu(
    data[data["infection"]=="INF"]["age"], 
    data[data["infection"]=="LN"]["age"], 
    nan_policy="omit"
)

data.groupby("infection")["sex"].value_counts(normalize=True)
```

## PCA between EW and MF (Rev II, Comment 5)

```{python}
candidates = ["IGHG3", "IGHG4", "ACTBL2", "IGLV9-49", "LCP1 PLS2", "SHBG", "ACTB", "FETUB", "S100A9 CAGB CFAG MRP14", "PFN1"]
```

```{python}
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

def plot_pca(
    pca_data, pca_var, pca_loadings, features, pc_x, pc_y,
    target = None, target_groups = None, alpha = 0.5, target_colors= None,
    annot=None, show_arrows=True, arrow_color = '#00000050', annot_color = '#00000050', arrow_alpha = 0.2, annot_alpha = 0.9,
    show_plot=False, show_legend=False, save_path=None, add_info=""):

        unsigned_range = lambda x: np.array([-abs(min(x)), abs(max(x))])
        print(unsigned_range)
        scl = np.max([
            unsigned_range(pca_loadings[:, pc_x]) / unsigned_range(pca_data[pc_x]),
            unsigned_range(pca_loadings[:, pc_y]) / unsigned_range(pca_data[pc_y])])
        pca_loadings = (pca_loadings/scl) 

        if target_groups != None:
            pca_data = pca_data[pca_data[target].isin(target_groups)]

        fig, ax = plt.subplots(1,1, figsize=(6,6))
        if target_groups== None:
            sns.scatterplot(data=pca_data, x=pc_x, y=pc_y, hue=target, alpha=alpha, edgecolor="k", palette=target_colors, linewidth=1.5, legend=False)
        else:
            sns.scatterplot(data=pca_data, x=pc_x, y=pc_y, hue=target, alpha=alpha, edgecolor="k", hue_order=target_groups, palette=target_colors, linewidth=1.5, legend=False)

        ax.set_ylabel(f"PC{pc_y+1} ({pca_var[pc_y]:.2f})", fontdict={"weight":"bold", "size":14})
        ax.set_xlabel(f"PC{pc_x+1} ({pca_var[pc_x]:.2f})", fontdict={"weight":"bold", "size":14})
        ax.set_yticklabels(ax.get_yticklabels(), fontweight="bold", fontsize=9)
        ax.set_xticklabels(ax.get_xticklabels(), fontweight="bold", fontsize=9)

        if annot != None:
            idx_features = [list(features).index(p) for p in annot]
            if not isinstance(annot, list):
                annot = list(annot)
        # Add Annotations and arrows
            for i, feature in zip(idx_features, annot):

                # Add the name of the variable near the arrow
                plt.annotate(feature, # variable name
                            (pca_loadings[i, pc_y], pca_loadings[i, pc_x]),
                            color=annot_color,
                            alpha=annot_alpha, fontsize=10)
                
                # Add an arrow representing the variable on the new axis
                ax.arrow(0, 0,
                        pca_loadings[i, pc_y],
                        pca_loadings[i, pc_x],
                        color=arrow_color,
                        alpha=arrow_alpha, 
                        width=0.01,
                        linestyle="--", head_width=0.2
                        ) 
        # overlay arrows with data_points
        if target_groups== None:
            sns.scatterplot(data=pca_data, x=pc_x, y=pc_y, hue=target, alpha=alpha, edgecolor="k", palette=target_colors,  linewidth=0.5)
        else:
            sns.scatterplot(data=pca_data, x=pc_x, y=pc_y, hue=target, alpha=alpha, edgecolor="k", hue_order=target_groups, palette=target_colors, linewidth=0.5)

        if show_legend != True:
            plt.legend().remove()
        plt.tight_layout()
        plt.grid(linestyle="--")
        if save_path != None:
            plt.savefig(os.path.join(save_path, f'pca_{target}{add_info}.png'),dpi=400)
        if show_plot:
            plt.show()
        else:
            plt.close()

def perform_pca(data, n_components=20):

    pca = PCA(n_components=n_components)
    
    data_scaled = StandardScaler().fit_transform(data)
    data_pca = pca.fit_transform(data_scaled)
    var_pca = pca.explained_variance_ratio_*100
    
    loadings = pca.components_.T #* np.sqrt(pca.explained_variance_ratio_)

    return data_pca, var_pca, loadings

```


```{python}

features_pca = ["IGHG3", "IGHG4", "ACTBL2", "IGLV9-49", "LCP1 PLS2", "SHBG", "PFN1"]

data_pca = data_imp[data_imp["disease severity"].isin(["EW", "MF"])]
data_pca = data_pca[common_proteins_imp].copy()
data_pca.columns = meta_table.loc[common_proteins_imp, "Gene Names"]
data_pca = data_pca[features_pca]


pca_data, pca_var, pca_loadings = perform_pca(
    data_pca[features_pca], n_components=5)

pca_data = pd.DataFrame(pca_data, index=data_pca.index)

pca_data_with_meta = pd.concat([
    pca_data,
    data_imp.loc[data_pca.index, ["disease severity", "sex"]]],
    axis=1) 

```

```{python}
pc_x = 0
pc_y = 1

plot_pca(
    pca_data_with_meta, pca_var, pca_loadings, features_pca, 
    pc_x=pc_x, pc_y=pc_y, alpha=0.9, show_plot=True,  target="disease severity", annot=features_pca, target_groups=["MF", "EW"], show_arrows=True,
    target_colors=[colors_severity["MF"], colors_severity["EW"]], 
    save_path=None, add_info="EWvsMF", show_legend=True)

plt.figure(figsize=(6,2))
sns.histplot(data=pca_data_with_meta[[pc_x, "disease severity"]], x=pc_x, hue="disease severity", palette=[colors_severity["EW"], colors_severity["MF"]], legend=False)
plt.xlabel("")
plt.tight_layout()
plt.show()
plt.figure(figsize=(6,2))
sns.histplot(data=pca_data_with_meta[[pc_y, "disease severity"]], x=pc_y, hue="disease severity", palette=[colors_severity["EW"], colors_severity["MF"]], legend=False)
plt.xlabel("")
plt.tight_layout()
plt.show()
```

Since only ACTB and IGHG4 signigficanlty differ, we suggest adding a scatterplot.

```{python}

meta_table[meta_table["Gene Names"].isin(["IGHG4", "ACTB"])]

x = "P01861"
y = "P60709"

fig = plt.figure(figsize=(6.5, 6.5))
gs = fig.add_gridspec(
    4, 4, 
    width_ratios=[0.5, 2, 0.5, 0.5],
    height_ratios=[0.5, 2, 0.5, 0.5])
ax0 = fig.add_subplot(gs[1:3, 0:2])

median_mf = matched_MF_EW.loc[
    matched_MF_EW["disease severity"]=="MF", [x, y]].median()
median_ew = matched_MF_EW.loc[
    matched_MF_EW["disease severity"]=="EW", [x, y]].median()

ax0.scatter(
    x=matched_MF_EW.loc[matched_MF_EW["disease severity"]=="MF", x], 
    y=matched_MF_EW.loc[matched_MF_EW["disease severity"]=="MF", y],  
    c=colors_severity["MF"], alpha=0.8, marker="o", label="")
ax0.scatter(
    x=median_mf[x], y=median_mf[y], 
    s=100, c=colors_severity["MF"], alpha=1, marker="o", label="median MF",
    ec="k", lw=2)

ax0.scatter(
    x=matched_MF_EW.loc[matched_MF_EW["disease severity"]=="EW", x], 
    y=matched_MF_EW.loc[matched_MF_EW["disease severity"]=="EW", y],  
    c=colors_severity["EW"], alpha=0.8, marker="^", label="")
ax0.scatter(
    x=median_ew[x], y=median_ew[y], 
    s=100, c=colors_severity["EW"], alpha=1, marker="^", label="median EW",
    ec="k", lw=2)
ax0.grid()
ax0.set_ylabel("$\\mathbf{log_2}$" + f"ACTB abundance", 
            fontweight="bold")
ax0.set_xlabel("$\\mathbf{log_2}$" + f" IGHG4 abundance", 
            fontweight="bold")
ax0.set_yticklabels(ax0.get_yticklabels(), 
            fontweight="bold")
ax0.set_xticklabels(ax0.get_xticklabels(), 
            fontweight="bold")
# ax0.legend()
# ax0.set_xlabel("log2 abundance IGHG4")
# ax0.set_ylabel("log2 abundance")
# plt.title("Matched Data")
# plt.tight_layout()
# plt.show()
plt.legend()

ax1 = fig.add_subplot(gs[1:3, 2])
sns.boxplot(ax=ax1,
    data=matched_MF_EW, x="disease severity", y=y, hue="disease severity",
    palette=[colors_severity["EW"], colors_severity["MF"]])
ax1.set_xlabel("")
ax1.set_ylabel("")
# ax1.set_xticks([])
ax1.set_yticks([])

ax1.set_xticklabels(ax1.get_xticklabels(), 
            fontweight="bold")

ax2 = fig.add_subplot(gs[0, 0:2])
sns.boxplot(ax=ax2,
    data=matched_MF_EW, y="disease severity", x=x, hue="disease severity",
    palette=[colors_severity["EW"], colors_severity["MF"]])
ax2.set_xlabel("")
ax2.set_ylabel("")
ax2.set_xticks([])
ax2.set_yticklabels(ax2.get_yticklabels(), 
            fontweight="bold")

plt.subplots_adjust(top=0.85, bottom=0.15, left=0.15, right=0.85)


# plt.tight_layout()
plt.show()
```

Select matched 


## Peptide Selection for MRM-HR Panel

```{python}
pept_data = pept_data.loc[data["filename"]]
pept_data = pept_data.astype(float)
pept_data = np.log2(pept_data+1)
pept_data = pept_data.replace({0.0:np.nan})
pept_data = pept_data.loc[:, pept_data.columns.get_level_values("Protein.Group").isin(meta_table.index)]
pept_data = pept_data.loc[:, pept_data.isna().mean() < 0.4]



pept_data.to_csv(
    os.path.join("data", "analysis", "loa", "pept_data_mrm.csv")
)
```


```{python}
matched_LN_INF = pd.read_csv(os.path.join(
    "data", "analysis", "loa", "matched", "data_matched_inf_ln_05.csv"), index_col=0)
matched_LN_EW = pd.read_csv(os.path.join(
    "data", "analysis", "loa", "matched", "data_matched_ew_ln_05.csv"), index_col=0)
matched_LN_MFEWMF = pd.read_csv(os.path.join(
    "data", "analysis", "loa", "matched", "data_matched_mfewmf_ln_05.csv"), index_col=0)
matched_MF_EW = pd.read_csv(os.path.join(
    "data", "analysis", "loa", "matched", "data_matched_mf_ew_05.csv"), index_col=0)
```




## load limma results 

Read in limma results from peptide comparisson
```{python}
limma_mf_ew_pept = pd.read_csv(os.path.join(res_path_tables, "dea_limma" ,"mf_ew_pept.csv"))
limma_ln_mfewmf_pept = pd.read_csv(os.path.join(res_path_tables, "dea_limma", "ln_mfewmf_05_pept.csv"))
limma_ln_inf_pept = pd.read_csv(os.path.join(res_path_tables, "dea_limma", "ln_infected_05_pept.csv"))
```

```{python}
pept_data_onecollevel = pept_data.copy()
pept_data_onecollevel.columns = pept_data.columns.get_level_values(0)
```

```{python}

pept_data_meta = data[["Sample ID", "filename", "sex", "age", "disease severity", "LLmf"]].merge(pept_data_onecollevel, left_on="filename", right_index=True)
```



```{python}
pept_sel = pd.read_excel(os.path.join("results", "loaloa", "review_1", "bestpept_selection_mrm.xlsx"))["Precursor"]

pept_data_meta = pept_data_meta[["Sample ID", "filename", "sex", "age", "disease severity", "LLmf"] + list(pept_sel.values)]

pept_data_meta = pept_data_meta[pept_data_meta["disease severity"].isin(["LN", "MF", "EWMF"])]


pept_data_meta = pept_data_meta.dropna(subset= [
    "TTPPVLDSDGSFFLYSR3", "SRWQEGNVFSC(UniMod:4)SVMHEALHNHYTQK4",
    "C(UniMod:4)PAPELLGGPSVFLFPPKPK4", "LNLAFIANLFNR2", "VAPDEHPILLTEAPLNPK3", "VDWYQQR2"])

```

```{python}
# MF vs LN 
sample_pairs = [
    "BDLL-P1090", "BDLL-P0037",
    "BDLL-P0362", "BDLL-P1216",
    "BDLL-P0559", "BDLL-P0356",
    "BDLL-P0761", "BDLL-P1098", 
    "BDLL-P0321", "BDLL-P1070", 
    "BDLL-P1104", "BDLL-P0775", 
    "BDLL-P0769", "BDLL-P1107", 
    "BDLL-P0341", "BDLL-P1130",
    "BDLL-P1060", "BDLL-P1080",
    "BDLL-P0220", "BDLL-P0995",
]
```

```{python}

from scipy.stats import mannwhitneyu
pept_data_meta_sel = pept_data_meta[pept_data_meta["Sample ID"].isin(sample_pairs)]

pept_info = pept_data.columns.to_frame()
for pept in pept_sel:
    stat, p = mannwhitneyu(
        pept_data_meta_sel.loc[pept_data_meta_sel["disease severity"]=="LN", pept],
        pept_data_meta_sel.loc[pept_data_meta_sel["disease severity"]=="MF", pept], nan_policy="omit"
    )

    sns.boxplot(data=pept_data_meta_sel, x="disease severity", y=pept)
    sns.stripplot(data=pept_data_meta_sel, x="disease severity", y=pept)
    plt.ylabel(" ".join(pept_info.loc[pept_info["Precursor.Id"]==pept, ["Genes", "Precursor.Id"]].values[0]))
    plt.title(f"p: {p:.5f}")
    plt.show()
```


```{python}
pept_data.loc[:, pept_data.columns.get_level_values("Genes").isin(["ACTBL2", "IGHG3", "IGHG4", "LCP1", "IGLV9-49"])].columns.to_frame().reset_index(drop=True).to_csv(os.path.join(
    "results", "loaloa", "review_1", "20250316_mrm_peptides_loa.csv"))
```


```{python}
pept_data_meta.loc[pept_data_meta["LLmf"]>300,["Sample ID", "sex", "age", "LLmf"]].dropna(subset=["LLmf", "age"]).sort_values(by=["sex", "age"]) # selection MF

pept_data_meta.loc[
    (pept_data_meta["disease severity"]=="LN") & 
    (pept_data_meta["sex"]==1) & 
    (pept_data_meta["age"]>62),["Sample ID", "sex", "age", "LLmf"]].dropna(subset=["age"]).sort_values(by="age") # selection LN

```


```{python}
meta_measurement_loa = pd.read_excel(r"data\meta_measurement\20230719_AF_50-0127_metadata_Loaloa.xlsx")

meta_measurement_loa = meta_measurement_loa.loc[meta_measurement_loa["Sample ID"].isin(sample_pairs), ["Sample ID", "Analysis.Plate", "Analysis.Row", "Analysis.Column", "Analysis.Plate96", "Analysis.Row96", "Analysis.Column96"]]
```

```{python}
data_sel_mrm = data.loc[data["Sample ID"].isin(sample_pairs), ["Sample ID" ,"age", "sex", "infection", "filename"]]


data_sel_mrm = data_sel_mrm.merge(meta_measurement_loa, left_on = "Sample ID", right_on = "Sample ID")
data_sel_mrm = data_sel_mrm.set_index("Sample ID")
data_sel_mrm = data_sel_mrm.loc[sample_pairs]
data_sel_mrm["matched_samples"] = list(np.ravel([[i, i] for i in range(1,11)]))

data_sel_mrm.to_csv(os.path.join(
    "results", "loaloa", "review_1", "20250316_mrm_samples_loa.csv"))

```

## MRM Results

DIA Discovery peptides

```{python}
pept_data = pd.read_table(os.path.join(
    "data", "preprocessing_boris", "NTD_min1peptides","NTD_min1peptides_PrecursorQuantity_reprep_normalized.tsv"
))

pept_data = pept_data.iloc[2:]
# 
pept_data.columns = ["Precursor.Id", "Stripped.Sequence", "Protein.Group", "Genes"] + list(pept_data.columns)[4:] 
pept_data=pept_data.T
pept_data
filenames = pept_data.index[4:]
# multi_index = pd.MultiIndex.from_frame(pept_data.iloc[:4].T)
# pept_data = pept_data.iloc[4:].reset_index(drop=True)
# pept_data.columns = multi_index
# pept_data.index = filenames
pept_data.columns = pept_data.iloc[0]
pept_data = pept_data.iloc[4:]
pept_data
```

Correlation Discovery 

```{python}
pept_meta = data.loc[data["Sample ID"].isin(sample_pairs), ["Sample ID", "filename"]]

pept_meta = pept_meta.merge(pept_data, left_on="filename", right_index=True)
pept_meta = pept_meta.set_index("Sample ID")
pept_meta.iloc[:, 2:] = np.log2(pept_meta.iloc[:, 2:].astype(float)+1)

pept_meta.loc["BDLL-P0356", "SC(UniMod:4)DTPPPC(UniMod:4)PR2"] = 17.32595633004369
pept_meta.loc["BDLL-P0321", "SC(UniMod:4)DTPPPC(UniMod:4)PR2"] = 20.09594558334798

pept_meta.loc["BDLL-P0995", "VYALPEDLVEVNPK2"] = 10.13720330938363
pept_meta.loc["BDLL-P1104", "VYALPEDLVEVNPK2"] = 11.36468185586456

pept_meta.loc["BDLL-P1107", "VYALPEDLVEVNPK2"] = 10.689539934419718
pept_meta.loc["BDLL-P0356", "VYALPEDLVEVNPK2"] = 11.553419112392382

```

pept_meta

```{python}
mrm_data = pd.read_csv(
    "data/analysis/loa/20250411_export_MRM_skylineoutput_new.csv", index_col="Sample ID")

mrm_data = mrm_data.dropna(subset="infection")

# mrm_data = mrm_data[mrm_data["Type"]=="precursor"]
mrm_data = mrm_data[mrm_data["Type"]=="sum_fragment"]

mrm_data["Area_log2"] = np.log2(mrm_data["Area"]+1)

stat_results = pd.DataFrame(columns=["gene", "p"], index=mrm_data["Precursor"].unique())


np.round(mrm_data.groupby("sex")["infection"].value_counts(normalize=True),2)
```


```{python}
mrm_precursor = ["VDWYQQR_2", "SCDTPPPCPR_3", "TYTCNVDHKPSNTK_4", "VYALPEDLVEVNPK_3", "VAPDEHPILLTEAPLNPK_3"]
dia_precursor = ["VDWYQQR2", "SC(UniMod:4)DTPPPC(UniMod:4)PR2", "TYTC(UniMod:4)NVDHKPSNTK3", "VYALPEDLVEVNPK2"]

genes = ["IGHG4", "IGLV9-49", "IGHG3", "ACTBL2", "LCP1"]

mrm_precursor = [
    "TYTCNVDHKPSNTK_4", "VGTGGIVGSK_1", "SCDTPPPCPR_2", "VAPDEHPILLTEAPLNPK_3", 
    "VYALPEDLVEVNPK_3"]

dia_precursor = [
    "YGPPC(UniMod:4)PSC(UniMod:4)PAPEFLGGPSVFLFPPKPK4", 
    "VGTGGIVGSK2", "SC(UniMod:4)DTPPPC(UniMod:4)PR2", "VAPDEHPILLTEAPLNPK3",
    "VYALPEDLVEVNPK2"]

for pre in range(5):
    data_corr_p = pd.concat(
        [
            mrm_data.loc[mrm_data["Precursor"]==mrm_precursor[pre], ["Area_log2", "infection"]],
            pept_meta[dia_precursor[pre]]
        ], axis=1)

    data_corr_p = data_corr_p.replace(0, np.nan)
    data_corr_p = data_corr_p.dropna(subset=[dia_precursor[pre]])
    m,b = np.polyfit(data_corr_p.loc[:, dia_precursor[pre]].astype(float), data_corr_p.loc[:, "Area_log2"].values,deg=1)

    s_rho, p = spearmanr(
        data_corr_p["Area_log2"], data_corr_p[dia_precursor[pre]], nan_policy="omit"
    )

    fig, ax = plt.subplots(1,1, figsize=(4,4))
    ax.plot(
        data_corr_p.loc[:, dia_precursor[pre]].astype(float), 
        m*data_corr_p.loc[:, dia_precursor[pre]].astype(float).values+b, lw=1, c="k", ls="--")
    sns.scatterplot(
        ax=ax, data=data_corr_p, x=dia_precursor[pre], 
        y="Area_log2", hue="infection", hue_order = ["LN", "INF"], palette=[colors_infection["LN"], colors_infection["INF"]], legend=False)
    ax.set_title("$s_{rho}$ "+ f"{s_rho:.2f}, p: {p:.2e}")
    
    x_lim = ax.get_xlim()
    y_lim = ax.get_ylim()
    ax.set_xlim(x_lim)
    ax.set_ylim(y_lim)
    fig.suptitle(genes[pre], fontweight="bold")


        
    ax.set_xlabel("$\\mathbf{log_{2}}$ " + "Abund. Discovery", fontweight="bold")
    ax.set_ylabel("$\\mathbf{log_{2}}$ " + "Abund. Validation", fontweight="bold")
    ax.grid()
    
    plt.tight_layout()
    plt.savefig(os.path.join(
        "results", "loaloa", "review_1", "mrm_panel", f"corr_{genes[pre]}.png"
    ), dpi=400)
    plt.show()
```

Bland - Altman - Plots 

```{python}
def bland_altman_plot(data1, data2, hue, title):
    data1     = np.asarray(data1)
    data2     = np.asarray(data2)
    mean_vals = np.median([data1, data2], axis=0)
    median      = np.median([data1, data2], axis=0)
    diff      = data1 - data2 
       
    median_diff = np.median(diff)
    diff = diff - median_diff
    median = 0

    lower_limit = np.percentile(diff, 2.5)
    upper_limit = np.percentile(diff, 97.5)

    print(len(mean_vals))
    
    for i in range(len(diff)):
        c = colors_infection["LN"] if  hue[i] =="LN" else colors_infection["INF"]
        plt.scatter(mean_vals[i], diff[i], color=c)
    plt.axhline(median, color='gray', linestyle='--', label='Median Diff.')
    plt.axhline(lower_limit, color='red', linestyle='--', label='2.5th percentile')
    plt.axhline(upper_limit, color='red', linestyle='--', label='97.5th percentile')
    plt.ylabel("Median Difference (Discovery - Validation) - shifted", fontweight="bold")
    plt.xlabel("Median (Discovery, Validation)", fontweight="bold")
    plt.title(title, fontweight="bold")
    plt.legend()
    plt.ylim([-3.2, 1.7])
    plt.tight_layout()
    plt.savefig(os.path.join(
        "results", "loaloa", "review_1", "mrm_panel", f"BA_{title}_medianshift_limits.png"
    ), dpi=400)
    plt.show()


for pre in range(5):
    data_corr_p = pd.concat(
        [
            mrm_data.loc[
                mrm_data["Precursor"]==mrm_precursor[pre], 
                ["Area_log2", "infection"]],
            pept_meta[dia_precursor[pre]]
        ], axis=1)
    data_corr_p = data_corr_p.replace(0, np.nan)
    data_corr_p = data_corr_p.dropna(subset=[dia_precursor[pre]])

    bland_altman_plot(
        data_corr_p[dia_precursor[pre]], 
        data_corr_p["Area_log2"],
        data_corr_p["infection"],
        genes[pre])   
    
```

Correlation MRM vs DIA ZenoTof

```{python}
pept_data_zeno = pd.read_csv(
    "data/analysis/loa/report_dia_validation.tsv", sep="\t")
```

No peptide found for ACTBL2

```{python}
pept_data_zeno[pept_data_zeno["Genes"]=="IGHG3"]["Stripped.Sequence"].drop_duplicates()
```

mrm_precursor = [
    "TYTCNVDHKPSNTK_4", "VGTGGIVGSK_1", "SCDTPPPCPR_2", "VAPDEHPILLTEAPLNPK_3", 
    "VYALPEDLVEVNPK_3"]

```{python}
precursor_ids_zenoDIA = [
    "TYTC(UniMod:4)NVDHKPSNTK4",
    "VGTGGIVGSK2",
    'SC(UniMod:4)DTPPPC(UniMod:4)PR2',
    "",
    "VYALPEDLVEVNPK2"

]
``` 

```{python}
pept_data_zeno[pept_data_zeno["Stripped.Sequence"]=="VYALPEDLVEVNPK"]
```

MRM Panel Boxplots

```{python}
for gene in mrm_data["Genes"].unique():
    mrm_g = mrm_data[mrm_data["Genes"]==gene]

    print(gene)

    for pre in mrm_g["Precursor"].unique():
        mrm_g_p = mrm_g[mrm_g["Precursor"]==pre]

        _, p = mannwhitneyu(
            mrm_g_p[mrm_g_p["infection"]=="INF"]["Area_log2"],
            mrm_g_p[mrm_g_p["infection"]=="LN"]["Area_log2"]
        )
        stat_results.loc[pre, "p"] = p
        stat_results.loc[pre, "gene"] = gene
        fig, ax = plt.subplots(1,1, figsize=(2,3))
        sns.boxplot(
            ax=ax, data=mrm_g_p, x="infection", y="Area_log2",
             fill=False, palette=[colors_infection["LN"], colors_infection["INF"]], order=["LN", "INF"],
             fliersize=0
        )
        sns.stripplot(
            ax=ax, data=mrm_g_p, x="infection", y="Area_log2",
            palette=[colors_infection["LN"], colors_infection["INF"]], order=["LN", "INF"]
        )
        ax.set_ylabel("$\\mathbf{log_{2}}$" + " area "+ f"{gene}\n{pre.split('_')[0]}", fontweight="bold")
        ax.set_xlabel(f"")
        ax.set_yticklabels(ax.get_yticklabels(), 
            fontweight="bold")
        ax.set_xticklabels(ax.get_xticklabels(), 
            fontweight="bold")
        ax.grid()
# ax0.legend()
        plt.title(f"p: {p:.2e}")
        plt.tight_layout()
        plt.savefig(f"results/loaloa/review_1/mrm_panel/{gene}_{pre}{'_signif' if p < 0.05 else ''}.png", dpi=300)

        # plt.close()
        # break
    # break
```

We check whether the discovery data RT anntoation for DIA-NN was correct by using the -vis command in DIA-NN and checking the TIC.

```{python}
filenames_mrm_samples = data[data["Sample ID"].isin(sample_pairs)]["filename"]

file_path = "/s-mcpb-ms03/union/is/PRO3/Data/50-0127/"
file_paths_disc = filenames_mrm_samples.values
file_paths_disc = ["--f " + file_path + fn + ".d" for fn in filenames_mrm_samples]
file_paths_disc = pd.Series(file_paths_disc).drop_duplicates().to_list()

#write  file
with open(os.path.join("data", "cfg", "20250415_loa_mrm_tic.cfg"), "w") as f:
    for fn in file_paths_disc:
        f.write(fn+"\n")
```



## OSPP in LOA

```{python}
data_ospp_long = pd.read_table(os.path.join(
    "data", "diann_output_reports", "cldi10@20250311+1200_50-0127_LoaLabeledPeptidesDiogenes", "report_osppRatio.tsv"
))
data_ospp_long["features"] = data_ospp_long["Genes"] + ":" + data_ospp_long["Stripped.Sequence"]+data_ospp_long["Precursor.Charge"].astype(str) 

data_ospp_long["Sample.Type"] = "biological"
data_ospp_long.loc[
    data_ospp_long["Run"].str.contains("BSA-Cal"), "Sample.Type"] = "Cal"
data_ospp_long.loc[
    data_ospp_long["Run"].str.contains("QC-Cal"), "Sample.Type"] = "Cal.QC"
data_ospp_long.loc[
    data_ospp_long["Run"].str.contains("QC-\d{3}"), "Sample.Type"] = "QC"
data_ospp_long = data_ospp_long.sort_values(
    by=["Genes" ,"Stripped.Sequence", "Precursor.Charge"])
data_ospp_long_qc = data_ospp_long[data_ospp_long["Sample.Type"]=="QC"]
data_ospp_long_bio = data_ospp_long[data_ospp_long["Sample.Type"]=="biological"]
data_ospp_long_cal = data_ospp_long[data_ospp_long["Sample.Type"]=="Cal"]
data_ospp_long_calqc = data_ospp_long[data_ospp_long["Sample.Type"]=="Cal.QC"]

features = data_ospp_long["features"].unique()

data_ospp = data_ospp_long.pivot(index ="Run", columns="features", values="ratio")
data_ospp_qc = data_ospp_long_qc.pivot(index ="Run", columns="features", values="ratio")
data_ospp_bio = data_ospp_long_bio.pivot(index ="Run", columns="features", values="ratio")
data_ospp_cal = data_ospp_long_cal.pivot(index ="Run", columns="features", values="ratio")
data_ospp_calqc = data_ospp_long_calqc.pivot(index ="Run", columns="features", values="ratio")
```

```{python}
data_ospp_qc = data_ospp_long_qc.pivot(index ="Run", columns="features", values="ratio")

# data_ospp_qc.isna().mean().hist()
# filter qc samples with less than 2/3 % completeness, 4 qc excluded
data_ospp_qc = data_ospp_qc.loc[data_ospp_qc.isna().mean(axis=1)<2/3, :]
# filter features with less than 66& completen, 67 precursor excluded
data_ospp_qc = data_ospp_qc.loc[:, data_ospp_qc.isna().mean()<1/3]
features_filt = data_ospp_qc.columns
```

```{python}
# Update Dataframes
data_ospp = data_ospp[features_filt]
data_ospp_qc = data_ospp_qc[features_filt]
data_ospp_bio = data_ospp_bio[features_filt]
data_ospp_cal = data_ospp_cal[features_filt]
data_ospp_calqc = data_ospp_calqc[features_filt]

data_ospp_long = data_ospp_long[data_ospp_long["features"].isin(features_filt)]
data_ospp_long_qc = data_ospp_long_qc[data_ospp_long_qc["features"].isin(features_filt)]
data_ospp_long_bio = data_ospp_long_bio[data_ospp_long_bio["features"].isin(features_filt)]
data_ospp_long_cal = data_ospp_long_cal[data_ospp_long_cal["features"].isin(features_filt)]
data_ospp_long_calqc = data_ospp_long_calqc[data_ospp_long_calqc["features"].isin(features_filt)]
```



```{python}
# Plot Distributions of features in Pools

for feat in features_selected:
    fig, axs = plt.subplots(1,3)
    sns.kdeplot(
        ax=axs[0],
        data=data_ospp,
        x=feat, c="k")
    sns.kdeplot(
        ax=axs[1],
        data=data_ospp_bio,
        x=feat, c="gray")
    sns.kdeplot(
        ax=axs[2],
        data=data_ospp_qc,
        x=feat, c="tab:blue")
    axs[0].set_title("All")
    axs[1].set_title("Study")
    axs[2].set_title("Pool QC")
    for ax in axs:
        ax.set_xlabel("")
        ax.set_ylabel("")

    fig.supxlabel(feat)
    fig.supylabel("Density")
    plt.tight_layout()
    
    plt.savefig(os.path.join(
        res_path_plots, "OSPP", "distributions", f'distr_{feat.replace(":","-")}.png'))


```

```{python}
peptide_meta = data_ospp_long[["Genes", "Stripped.Sequence", "Precursor.Charge", "features"]].drop_duplicates()
peptide_meta= peptide_meta.sort_values(
    by=["Genes" ,"Stripped.Sequence", "Precursor.Charge"])


def coef_of_variation(data):
    median_value = np.nanmedian(data)
    
    # Calculate MAD
    mad = np.nanmedian(np.abs(data - median_value))
    
    # Calculate CV as (MAD / Median) * 100
    cv = (mad / median_value) * 100
    return cv

cv_all = data_ospp.apply(lambda col: coef_of_variation(col), axis=0)
cv_bio = data_ospp_bio.apply(lambda col: coef_of_variation(col), axis=0)
cv_qc = data_ospp_qc.apply(lambda col: coef_of_variation(col), axis=0)

med_abund_all = data_ospp.median()
med_abund_bio = data_ospp_bio.median()
med_abund_qc = data_ospp_qc.median()


# pd.DataFrame({
#     "cv_all":cv_all, "cv_qc":cv_qc, "cv_bio":cv_bio,
#     "mvr_all": data_ospp.isna().mean(),
#     "mvr_bio": data_ospp_bio.isna().mean(),
#     "mvr_qc": data_ospp_qc.isna().mean(),
#     "medAbund_all":med_abund_all, 
#     "medAbund_bio":med_abund_bio,
#     "medAbund_qc":med_abund_qc
# }).to_csv(
#     os.path.join(res_path_tables, "OSPP", "diagnostics_peptides.csv")
# )

```


```{python}
meta_ospp_sel = pd.read_csv(
    os.path.join(res_path_tables, "OSPP", "diagnostics_peptides_selection.csv"),
    index_col=0
)

meta_ospp_sel = meta_ospp_sel[meta_ospp_sel["Selected"]==True]
features_selected = meta_ospp_sel.index

```

```{python}
data_ospp_cal["cal_index"] = [int(x.split("-")[-1]) for x in data_ospp_cal.index]
fig, ax = plt.subplots(1,1, figsize=(5,30))
sns.heatmap(
    data_ospp_cal.groupby("cal_index")[features_selected].apply(lambda x: x.isna().mean()).T,
    linewidths=0.00)
```

Extract Calibration Curves
```{python}

data_ospp_cal_log10 = np.log10(data_ospp_cal)
data_ospp_cal_log10["cal_index"] = [int(x.split("-")[-1]) for x in data_ospp_cal.index]

for feat in features_selected:
    fig, ax = plt.subplots(1,1)
    sns.boxplot(ax=ax,
        data=data_ospp_cal_log10,
        x="cal_index", legend=False,
        y=feat, fill=False, fliersize=0
    )
    sns.stripplot(ax=ax,
        data=data_ospp_cal_log10,
        x="cal_index", legend=False,
        y=feat, alpha=0.5, c="k"
    )

    # add calibration fit
    m, b = np.polyfit(
        y=data_ospp_cal_log10.groupby("cal_index")[feat].median().iloc[1:7].values, 
        x=range(1,7), deg=1)
    ax.plot(m * range(0,10) +b, c="gray", ls="--", label=f"y={m:.2f}*x+{b:.2f} ")

    sns.boxplot(ax=ax,
        data=np.log10(data_ospp_bio),
        y=feat, x=9 , fill=False, legend=False,
    )
    sns.stripplot(ax=ax,
        data=np.log10(data_ospp_bio), legend=False,
        y=feat, x=9 ,alpha=0.5, c="k", dodge=True
    )
    sns.boxplot(ax=ax,
        data=np.log10(data_ospp_qc),
        y=feat, x=10 , fill=False, legend=False,
    )
    sns.stripplot(ax=ax,
        data=np.log10(data_ospp_qc), legend=False,
        y=feat, x=10 ,alpha=0.5, c="k", dodge=True
    )
    plt.ylabel(f"-log10 {feat}")
    plt.xlabel(f"Spiked Standard in ng/µl")
    ax.set_xticklabels(["2700","900","300","90","30","9","3","0"]+[ "Samples", "Pools"])
    plt.legend()
    plt.tight_layout()
    plt.savefig(
        os.path.join(
            res_path_plots, "OSPP" ,"dilution_series", f'dilution_{feat.replace(":","-")}.png'
        )
    )
    plt.close()
```



```{python}
for feat in features_selected:
    fig, axs = plt.subplots(1,3)
    sns.kdeplot(
        ax=axs[0],
        data=data_ospp_norm,
        x=feat, c="k")
    sns.kdeplot(
        ax=axs[1],
        data=data_ospp_bio_norm,
        x=feat, c="gray")
    sns.kdeplot(
        ax=axs[2],
        data=data_ospp_qc_norm,
        x=feat, c="tab:blue")
    axs[0].set_title("All")
    axs[1].set_title("Study")
    axs[2].set_title("Pool QC")
    for ax in axs:
        ax.set_xlabel("")
        ax.set_ylabel("")

    fig.supxlabel(feat)
    fig.supylabel("Density")
    plt.tight_layout()
    
    plt.savefig(os.path.join(
        res_path_plots, "OSPP", "distributions", f'distr_{feat.replace(":","-")}_norm.png'))

```

```{python}
data_ospp_cal_norm_log10 = -np.log10(data_ospp_cal_norm)
data_ospp_cal_norm_log10["cal_index"] = [int(x.split("-")[-1]) for x in data_ospp_cal_norm.index]

for feat in features_selected:
    fig, ax = plt.subplots(1,1)
    sns.boxplot(ax=ax,
        data=data_ospp_cal_norm_log10,
        x="cal_index", legend=False,
        y=feat, fill=False, fliersize=0
    )
    sns.stripplot(ax=ax,
        data=data_ospp_cal_norm_log10,
        x="cal_index", legend=False,
        y=feat, alpha=0.5, c="k"
    )

    # add calibration fit
    m, b = np.polyfit(
        y=data_ospp_cal_norm_log10.groupby("cal_index")[feat].median().iloc[1:7].values, 
        x=range(1,7), deg=1)
    ax.plot(m * range(0,10) +b, c="gray", ls="--", label=f"y={m:.2f}*x+{b:.2f} ")

    sns.boxplot(ax=ax,
        data=-np.log10(data_ospp_bio_norm),
        y=feat, x=9 , fill=False, legend=False,
    )
    sns.stripplot(ax=ax,
        data=-np.log10(data_ospp_bio_norm), legend=False,
        y=feat, x=9 ,alpha=0.5, c="k", dodge=True
    )
    sns.boxplot(ax=ax,
        data=-np.log10(data_ospp_qc_norm),
        y=feat, x=10 , fill=False, legend=False,
    )
    sns.stripplot(ax=ax,
        data=-np.log10(data_ospp_qc_norm), legend=False,
        y=feat, x=10 ,alpha=0.5, c="k", dodge=True
    )
    plt.ylabel(f"-log10 {feat}")
    plt.xlabel(f"Dilution Step")
    ax.set_xticklabels(["1","2","3","4","5","6","7","8", "Samples", "Pools"])
    plt.legend()
    plt.tight_layout()
    plt.savefig(
        os.path.join(
            res_path_plots, "OSPP" ,"dilution_series", f'dilution_{feat.replace(":","-")}_norm.png'
        )
    )
    plt.close()
```




## PCA Color by Curve step

Heatmap missingness calibration curves,
probably some peptides are not detected at the lower end 

```{python}
# PCA Calibration

features_pca = features_selected

data_pca = data_ospp_cal

data_pca = pd.DataFrame(
    KNNImputer().fit_transform(data_pca), index=data_pca.index,
    columns=data_pca.columns)

pca_data, pca_var, pca_loadings = perform_pca(
    data_pca[features_pca], n_components=20)

pca_data = pd.DataFrame(pca_data, index=data_pca.index)

pca_data["cal_index"] = [int(x.split("-")[-1]) for x in data_ospp_cal.index]

plot_pca(
    pca_data, pca_var, pca_loadings, features_pca, 
    pc_x=0, pc_y=1, alpha=0.9, show_plot=True,  target="cal_index", 
    annot=None, target_groups=range(1,9), show_arrows=True,
    target_colors=sns.color_palette("tab10"), 
    save_path=None, add_info="Calibration", show_legend=True)
plot_pca(
    pca_data.drop("20230602_PRO3_AF_000_50-0127_Loaloa-384_P00_BSA-Cal-1"), pca_var, pca_loadings, features_pca, 
    pc_x=0, pc_y=1, alpha=0.9, show_plot=True,  target="cal_index", 
    annot=None, target_groups=range(1,9), show_arrows=True,
    target_colors=sns.color_palette("tab10"), 
    save_path=None, add_info="Calibration", show_legend=True)


data_ospp_cal = data_ospp_cal.drop(
    "20230602_PRO3_AF_000_50-0127_Loaloa-384_P00_BSA-Cal-1")

```


```{python}
# PCA Biological samples and qcs
features_pca = features_selected

outlier_samples_first_pca = ['20230605_PRO3_AF_846_50-0127_Loaloa-384_P00_QC-044',
       '20230605_PRO3_AF_846_50-0127_Loaloa-384_P00_QC-045',
       '20230605_PRO3_AF_846_50-0127_Loaloa-384_P00_QC-046',
       '20230608_PRO3_AF_549_50-0127_Loaloa-384_P00_QC-000',
       '20230608_PRO3_AF_550_50-0127_Loaloa-384_P00_QC-001',
       '20230608_PRO3_AF_551_50-0127_Loaloa-384_P00_QC-002']

data_ospp_qc = data_ospp_qc.drop(outlier_samples_first_pca)

data_pca = pd.concat([
    data_ospp_bio,
    data_ospp_qc
])

data_pca = pd.DataFrame(
    KNNImputer().fit_transform(data_pca), index=data_pca.index,
    columns=data_pca.columns)

pca_data, pca_var, pca_loadings = perform_pca(
    data_pca[features_pca], n_components=20)

pca_data = pd.DataFrame(pca_data, index=data_pca.index)

pca_data["Sample.Type"] = ["Study"]*data_ospp_bio.shape[0] + ["Pool"]*data_ospp_qc.shape[0]
pca_data["Median Exp"] = list(data_ospp_bio.median(axis=1)) + list(data_ospp_qc.median(axis=1))
pca_data["Inj.Number"] = [x.split("_")[3] for x in data_pca.index]
pca_data["MS.Date"] = [x.split("_")[0] for x in data_pca.index]
plot_pca(
    pca_data, pca_var, pca_loadings, features_pca, 
    pc_x=0, pc_y=1, alpha=0.9, show_plot=True,  target="Sample.Type", 
    annot=None, target_groups=["Study", "Pool"], show_arrows=True,
    target_colors=["gray", "tab:blue"], 
    save_path=None, add_info="Calibration", show_legend=True)
plot_pca(
    pca_data, pca_var, pca_loadings, features_pca, 
    pc_x=1, pc_y=2, alpha=0.9, show_plot=True,  target="Sample.Type", 
    annot=None, target_groups=["Study", "Pool"], show_arrows=True,
    target_colors=["gray", "tab:blue"], 
    save_path=None, add_info="Calibration", show_legend=True)
plot_pca(
    pca_data, pca_var, pca_loadings, features_pca, 
    pc_x=1, pc_y=2, alpha=0.9, show_plot=True,  target="MS.Date", 
    annot=None, target_groups=None, show_arrows=True,
    target_colors=sns.color_palette("tab10"), 
    save_path=None, add_info="Calibration", show_legend=True)
plot_pca(
    pca_data, pca_var, pca_loadings, features_pca, 
    pc_x=0, pc_y=1, alpha=0.9, show_plot=True,  target="Inj.Number", 
    annot=None, target_groups=None, show_arrows=True,
    target_colors=sns.color_palette("Greens"), 
    save_path=None, add_info="Calibration", show_legend=False)
plot_pca(
    pca_data, pca_var, pca_loadings, features_pca, 
    pc_x=0, pc_y=1, alpha=0.9, show_plot=True,  target="Median Exp", 
    annot=None, target_groups=None, show_arrows=True,
    target_colors=sns.color_palette("Reds"), 
    save_path=None, add_info="Calibration", show_legend=False)
```

## Differential Expression Analysis

```{python}
# data = data.set_index("filename")
data = data.loc[data_ospp_bio.index]
```

```{python}
features_pca = features_selected
data_pca = data_ospp_bio

data_pca = pd.DataFrame(
    KNNImputer().fit_transform(data_pca), index=data_pca.index,
    columns=data_pca.columns)

pca_data, pca_var, pca_loadings = perform_pca(
    data_pca[features_pca], n_components=20)

pca_data = pd.DataFrame(pca_data, index=data_pca.index)

pca_data["disease severity"] = data["disease severity"]
pca_data["infection"] = data["infection"]

plot_pca(
    pca_data, pca_var, pca_loadings, features_pca, 
    pc_x=0, pc_y=1, alpha=0.9, show_plot=True,  target="infection", 
    annot=None, target_groups=None, show_arrows=True,
    target_colors=[colors_infection["LN"], colors_infection["INF"]], 
    save_path=None, add_info="Infection", show_legend=False)

idx_ln_mf = data[data["disease severity"].isin(["LN", "MF", "EWMF"])].index
data_pca = data_ospp_bio.loc[idx_ln_mf]

data_pca = pd.DataFrame(
    KNNImputer().fit_transform(data_pca), index=data_pca.index,
    columns=data_pca.columns)

pca_data, pca_var, pca_loadings = perform_pca(
    data_pca[features_pca], n_components=20)

pca_data = pd.DataFrame(pca_data, index=data_pca.index)

pca_data["disease severity"] = data["disease severity"].loc[idx_ln_mf]
pca_data["infection"] = data["infection"].loc[idx_ln_mf]

plot_pca(
    pca_data, pca_var, pca_loadings, features_pca, 
    pc_x=1, pc_y=2, alpha=0.9, show_plot=True,  target="infection", 
    annot=None, target_groups=None, show_arrows=True,
    target_colors=[colors_infection["LN"], colors_infection["INF"]], 
    save_path=None, add_info="Infection", show_legend=False)
```

```{python}
d
```

Export data for limma anlysis

```{python}


data_ospp_bio_log2 = np.log2(data_ospp_bio[features_selected]+1)
data_ospp_bio_log2.to_csv(
    os.path.join("data", "analysis", "loa", "loa_data_05_ospp.csv")
)

```


```{python}
order = ["LN", "EW", "EWMF", "MF"]
colors = [colors_severity[g] for g in order]

data_ospp_bio_log2["disease severity"] = data["disease severity"]

for p in features_selected:  

    fig, ax = plt.subplots(1,1, figsize=(5, 5))
    sns.boxplot(ax=ax,
        data=data_ospp_bio_log2, y=p, x="disease severity", order=order,
        fill=False, fliersize=0, palette=colors)
    sns.stripplot(ax=ax,
        data=data_ospp_bio_log2, y=p, x="disease severity", order=order,
        palette=colors, edgecolor="gray", linewidth=1, alpha=.2)
    ax.set_ylabel("$\\mathbf{log_2}$ h/l ratio", 
            fontweight="bold")
    ax.set_xlabel("")
    ax.set_xticklabels(order, fontweight="bold")
    ax.set_yticklabels(ax.get_yticklabels(), fontweight="bold")
    ax.set_title(p, fontweight="bold")
    ax.grid()
    plt.tight_layout()
    plt.savefig(os.path.join(
        res_path_plots, "OSPP",  "boxplots", f'{p.replace(":","-")}.png'),
        dpi=400
    )
    plt.close()
```


Boxplots for OSPP Stnadard in EW and MF - and EW and LN Group
```{python}

matched_LN_INF = pd.read_csv(os.path.join(
    "data", "analysis", "loa", "matched", "data_matched_inf_ln_05.csv"), index_col=2)
matched_LN_EW = pd.read_csv(os.path.join(
    "data", "analysis", "loa", "matched", "data_matched_ew_ln_05.csv"), index_col=2)
matched_LN_MFEWMF = pd.read_csv(os.path.join(
    "data", "analysis", "loa", "matched", "data_matched_mfewmf_ln_05.csv"), index_col=2)
matched_MF_EW = pd.read_csv(os.path.join(
    "data", "analysis", "loa", "matched", "data_matched_mf_ew_05.csv"), index_col=2)

```

EW vs MF
```{python}
data_ospp_log10 = np.log10(data_ospp_bio[features_selected])

matched_LN_EW_ospp = matched_LN_EW.merge(
    data_ospp_log10, right_index=True, left_index=True)


for feat in [
    "IGHG3:WYVDGVEVHNAK2",
    "CD5L:IWLDNVR2",
    "IGHM:NVPLPVIAELPPK2",
    "SHBG:IALGGLLFPASNLR2",
    "SERPINA7:GWVDLFVPK2"]:
    fig, ax = plt.subplots(1,1, figsize=(2,4))
    sns.boxplot(
        data = matched_LN_EW_ospp,
        x="disease severity", y=feat,
        palette=[colors_severity["EW"], colors_severity["LN"]], fill=False
    )
    sns.stripplot(
        data = matched_LN_EW_ospp,
        x="disease severity", y=feat,
        palette=[colors_severity["EW"], colors_severity["LN"]]
    )
    ax.set_ylabel(f"log10 {feat}")
```

EW vs LN


```{python}
data_ospp_log10 = np.log10(data_ospp_bio[features_selected])

matched_LN_EW_ospp = matched_MF_EW.merge(
    data_ospp_log10, right_index=True, left_index=True)


for feat in [
    "IGHG4:GLPSSIEK2",
    "ACTB:EITALAPSTMK2"]:
    fig, ax = plt.subplots(1,1, figsize=(2,4))
    sns.boxplot(
        data = matched_MF_EW_ospp,
        x="disease severity", y=feat,
        palette=[colors_severity["EW"], colors_severity["MF"]], fill=False
    )
    sns.stripplot(
        data = matched_MF_EW_ospp,
        x="disease severity", y=feat,
        palette=[colors_severity["EW"], colors_severity["MF"]]
    )
    ax.set_ylabel(f"log10 {feat}")
```


# Mansonella analysis

```{python}
data_mans.rename(dict(zip(meta_table.index, [x.split(" ")[0] for x in meta_table["Gene Names"]])), axis=1)

data_mans = data_mans.drop(
    data_mans[(data_mans["eos_high"] == "1") & (data_mans["disease severity"] == "LN")].index)

proteins = [x.split(" ")[0] for x in meta_table["Gene Names"]]

data_mans["infection"] = data_mans["infection"].replace({
    "mansonella coinf": "CoMP",
    "mansonella": "MP",
    "malaria coinf": "CoMAL",
    "mansonella & malaria coinf": "CoMPMAL"
})

data_mans["severity"] = data_mans["disease severity"] + "_" + data_mans["infection"]

data_mans["severity"] = data_mans["severity"].replace({
    'EW_INF':"LLew", 
    'EWMF_INF': "LLewmf", 
    'LN_LN':"CTRL",
    'MP_MP':"MP", 
    'MF_INF':"LLmf",
    'EW_CoMP': "LLew_MP",
    'MF_CoMP': "LLmf_MP",
    'EWMF_CoMP': "LLewmf_MP",
})


groups_severity_mans = [
 'CTRL', 'MP', 'LLmf', 'LLewmf', 'LLew',
 ]
groups_severity_mans_coinf = [
 'CTRL', 'MP', 'LLmf', 'LLewmf', 'LLew',
 'EWMF_CoMAL', 'EWMF_CoMP', 'EWMF_CoMPMAL',
 'EW_CoMAL', 'EW_CoMP', 'EW_CoMPMAL',
  'MF_CoMAL', 'MF_CoMP', 'MF_CoMPMAL']

data_mans.to_csv(
    os.path.join("results", "mansonella", "20250815_data_mp.csv")
    )
```




## Cohort Statistics

per Group
N, Sex (%w), Median Age, median mans para, median ll_para 

per Protein
Study CV
Pool CV
Protein Name
r Mans Para
r Loa Para

N_Group
MV_Group
Median Abund_Group

Contrasts (Mann-Whitney U):
Mans HC
Mans vs Loa all
Mans vs Loa MF + EWMF
Mans vs Loa EW
Mans vs Mans + Loa MF  
Mans vs Mans + Loa EW

Groups:

```{python} 
res_path_mans = "results/mansonella"

df = data_mans[data_mans["severity"].isin(groups_severity_mans)]
groups = groups_severity_mans
alpha = 0.05

###

n_groups = df["severity"].value_counts().loc[groups]
n_groups.columns = ["N_group"]

q25_age =df.groupby("severity")["age"].quantile(0.25)
median_age =df.groupby("severity")["age"].median()
q75_age =df.groupby("severity")["age"].quantile(0.75)

_, p_age = kruskal(*[
    df[df["severity"]==g]["age"].dropna().values for g in groups
])
perc_sex_f = df.groupby("severity").apply(
    lambda g: (g['sex'] == 0).mean() * 100)

comb = list(combinations(groups, 2))

contingency_table_sex = pd.crosstab(df['sex'], df['severity'])
chi2, p_chi_sex, dof, expected = chi2_contingency(contingency_table_sex)

if p_chi_sex < alpha: 
    p_chi_sex_group = [chi2_contingency(pd.crosstab(
        df[df["severity"].isin(pair)]["sex"],
        df[df["severity"].isin(pair)]["severity"]))[1] for pair in list(combinations(groups, 2))]


median_ll_mf = df[df["ll_mf"].notna()].groupby("severity")["ll_mf"].median()
median_ll_mf_f = df[df["ll_mf"].notna()][
    df["sex"]==0].groupby("severity")["ll_mf"].median()
median_ll_mf_m = df[df["ll_mf"].notna()][
    df["sex"]==1].groupby("severity")["ll_mf"].median()
median_mp_mf = df[df["mp_mf"].notna()].groupby("severity")["mp_mf"].median()
median_mp_mf_f = df[df["mp_mf"].notna()][
    df["sex"]==0].groupby("severity")["mp_mf"].median()
median_mp_mf_m = df[df["mp_mf"].notna()][
    df["sex"]==1].groupby("severity")["mp_mf"].median()

overview_df = pd.concat([
    n_groups, 
    q25_age, median_age, q75_age, 
    perc_sex_f,
    median_ll_mf, median_ll_mf_f, median_ll_mf_m, 
    median_mp_mf, median_mp_mf_f, median_mp_mf_m], axis=1)

overview_df.columns = [
    "N_groups", "age_q25", "age_median", "age_75",
    "percSexF",
    "llmf_median", "llmf_median_sexF", "llmf_median_sexM",
    "mpmf_median", "mpmf_median_sexF", "mpmf_median_sexM",
]

p_mpfmf_sex = mannwhitneyu(df[(df["sex"]==0) & (df["mp_mf"]>0)]["mp_mf"], df[(df["sex"]==1) & (df["mp_mf"]>0)]["mp_mf"])[1]


mp_mf_gr0 = df[df["mp_mf"]>0].index
age_notna = df[df["age"].notna()].index
common_idx = list(set(mp_mf_gr0)&set(age_notna))
p_age_mf, r_age_mf = spearmanr(df.loc[common_idx, "mp_mf"], df.loc[common_idx, "age"])

stats_df_overview =pd.DataFrame(
    index = [f'vs'.join(pair) for pair in comb]
)
stats_df_overview["p_kruskal_age"] = p_age
stats_df_overview["p_chi_sex"] = p_chi_sex
stats_df_overview["p_chi_sex_group"] = p_chi_sex_group
stats_df_overview["p_u_mpf_mf_sex"] = p_mpfmf_sex
stats_df_overview["r_srho_age_mf"] = r_age_mf
stats_df_overview["p_srho_age_mf"] = p_age_mf

writer = pd.ExcelWriter(os.path.join(
    res_path_mans, "cohort_overview.xlsx"
))

with writer:
    overview_df.to_excel(
        writer, sheet_name="Overview_cohort", index=True)
    stats_df_overview.to_excel(
        writer, sheet_name="Stats_cohort", index=True)
```

```{python}
# Sample Sizes
n_per_group = pd.DataFrame(
    df.groupby("severity")[meta_table.index].count().T[groups])
n_per_group.columns = ["N_"+g for g in groups]

# Correlation with parasite count (MP and LL)
df_ll = df[df["ll_mf"]>0]
df_mp = df[df["mp_mf"]>0]
r_df = pd.DataFrame({
    "r_srho_mpmf": [spearmanr(df_mp[p], df_mp["mp_mf"], nan_policy="omit")[0] for p in meta_table.index],
    "p_srho_mpmf": [spearmanr(
    df_mp[p], df_mp["mp_mf"], nan_policy="omit")[1] for p in meta_table.index],
    "r_srho_llmf": [spearmanr(
    df_ll[p], df_ll["ll_mf"], nan_policy="omit")[0] for p in meta_table.index],
    "p_srho_llmf": [spearmanr(
    df_ll[p], df_ll["ll_mf"], nan_policy="omit")[1] for p in meta_table.index],
    
    }, index = meta_table.index
    )

groups_severity_kruskal = [
 'MP', 'LLmf', 'LLewmf', 'LLew',
 ]

# Severity Differences
## p-value for test over all groups
p_u_mpvsCTRL = pd.Series([mannwhitneyu(df[df["severity"]=="MP"][p], df[df["severity"]=="CTRL"][p], nan_policy="omit").pvalue for p in meta_table.index], index=meta_table.index, name="p_u_MPvsCTRL")
q_u_mpvsCTRL = pd.Series(multipletests(p_u_mpvsCTRL, method="fdr_bh")[1], index=meta_table.index, name="qfdr_u_MPvsCTRL")
p_kruskal_severity = pd.Series([kruskal(*[df[df["severity"]==g][p].dropna() for g in groups_severity_kruskal]).pvalue for p in meta_table.index], index=meta_table.index, name="p_kruskal_severity")
q_kruskal_severity = pd.Series(multipletests(p_kruskal_severity, method="fdr_bh")[1], index=meta_table.index, name="qfdr_kruskal_severity")
```

```{python}
fbc = df.columns[41:53]

# stats FBC

# df.groupby("severity")

median_mpvsCTRL_fbc = df.groupby("severity")[fbc].median()
q25_mpvsCTRL_fbc = df.groupby("severity")[fbc].quantile(0.25)
q75_mpvsCTRL_fbc = df.groupby("severity")[fbc].quantile(0.75)



p_u_mpvsCTRL_fbc = pd.Series([mannwhitneyu(df[df["severity"]=="MP"][f], df[df["severity"]=="CTRL"][f], nan_policy="omit").pvalue for f in fbc], index=fbc, name="p_u_MPvsCTRL_fbc") 
q_u_mpvsCTRL_fbc = pd.Series(multipletests(p_u_mpvsCTRL_fbc, method="fdr_bh")[1], index=fbc, name="qfdr_u_MPvsCTRL_fbc")


stats_fbc = pd.concat(
    [
        median_mpvsCTRL_fbc.loc[["CTRL", "MP"]].T, 
        q25_mpvsCTRL_fbc.loc[["CTRL", "MP"]].T, 
        q75_mpvsCTRL_fbc.loc[["CTRL", "MP"]].T, 
        p_u_mpvsCTRL_fbc,
        q_u_mpvsCTRL_fbc,
        ], axis=1)

stats_fbc.columns = [
    "median_CTRL",
    "median_MP",
    "q25_CTRL",
    "q25_MP",
    "q75_CTRL",
    "q75_MP",
    "p_u_MPvsCTRL",
    "qfdr_u_MPvsCTRL",
]
stats_fbc

```

```{python}
contrasts = [
    ('MP', 'CTRL'),
    ('LLmf', 'CTRL'),
    ('LLewmf', 'CTRL'),
    ('LLew', 'CTRL'),
    ('MP', 'LLmf'),
    ('MP', 'LLewmf'),
    ('MP', 'LLew'),
    ('LLmf', 'LLewmf'),
    ('LLmf', 'LLew'),
    ('LLewmf', 'LLew')]
## Post-Hoc tests
contrasts_median_fc = pd.DataFrame([[
    df.loc[df["severity"]==pair[0], p].median() - df.loc[df["severity"]==pair[1], p].median()
     for pair in contrasts] for p in meta_table.index],
    index=meta_table.index,
    columns = ["MedFC_" +"vs".join(pair) for pair in contrasts])
```


```{python}
# contrast = contrasts_median_fc["MedFC_MPvsCTRL"]

# cv_ci_df = pd.DataFrame()

# z_85 = 1.44 # 90% CI
# z_90 = 1.645 # 90% CI
# z_95 = 1.96 # 95% CI
# z_99 = 2.576 # 95% CI

# cv_ci_df['log2_thresh_85'] = np.log2(1 + z_85 * meta_table['CV_pool']/100)
# cv_ci_df['log2_thresh_90'] = np.log2(1 + z_90 * meta_table['CV_pool']/100)
# cv_ci_df['log2_thresh_95'] = np.log2(1 + z_95 * meta_table['CV_pool']/100)
# cv_ci_df['log2_thresh_99'] = np.log2(1 + z_99 * meta_table['CV_pool']/100)


# cv_ci_df['exceeds_noise_85'] = np.abs(contrast) > cv_ci_df['log2_thresh_85']
# cv_ci_df['exceeds_noise_90'] = np.abs(contrast) > cv_ci_df['log2_thresh_90']
# cv_ci_df['exceeds_noise_95'] = np.abs(contrast) > cv_ci_df['log2_thresh_95']
# cv_ci_df['exceeds_noise_99'] = np.abs(contrast) > cv_ci_df['log2_thresh_99']

```

```{python}

q_kruskal_signif = q_kruskal_severity[q_kruskal_severity<0.05].index

# posthoc tests for proteins differeing between infected groups

res_p_dunn_severity =  [posthoc_dunn([df[df["severity"]==g][p].dropna() for g in groups_severity_kruskal])  for p in q_kruskal_signif]
res_q_dunn_severity = [posthoc_dunn([df[df["severity"]==g][p].dropna() for g in groups_severity_kruskal], p_adjust="fdr_bh")  for p in q_kruskal_signif]

res_p_dunn_severity = [pd.DataFrame(p.values, index=groups_severity_kruskal, columns=groups_severity_kruskal) for p in res_p_dunn_severity]
res_q_dunn_severity = [pd.DataFrame(q.values, index=groups_severity_kruskal, columns=groups_severity_kruskal) for q in res_q_dunn_severity]

res_p_dunn_severity = [pd.DataFrame(p.values, index=groups_severity_kruskal, columns=groups_severity_kruskal).reset_index().melt(id_vars='index', var_name='colname', value_name='value') for p in res_p_dunn_severity]
res_q_dunn_severity = [pd.DataFrame(q.values, index=groups_severity_kruskal, columns=groups_severity_kruskal).reset_index().melt(id_vars='index', var_name='colname', value_name='value') for q in res_q_dunn_severity]

res_p_dunn_severity_lst = []
for df_p in res_p_dunn_severity:
    df_p["pair"] = df_p.apply(lambda row: tuple(sorted([row['index'], row['colname']])), axis=1)
    df_p = df_p[df_p["index"]!=df_p["colname"]]
    df_p = df_p.drop_duplicates(subset="pair")
    df_p.index = "p_dunn_" + df_p["colname"]+ "vs" + df_p["index"]
    df_p = df_p.drop(["index", "colname", "pair"], axis=1)
    res_p_dunn_severity_lst.append(df_p)

res_q_dunn_severity_lst = []
for df_q in res_q_dunn_severity:
    df_q["pair"] = df_q.apply(lambda row: tuple(sorted([row['index'], row['colname']])), axis=1)
    df_q = df_q[df_q["index"]!=df_q["colname"]]
    df_q = df_q.drop_duplicates(subset="pair")
    df_q.index = "qfdr_dunn_" + df_q["colname"]+ "vs" + df_q["index"]
    df_q = df_q.drop(["index", "colname", "pair"], axis=1)
    res_q_dunn_severity_lst.append(df_q)



res_p_dunn_severity = pd.concat([p.T for p in res_p_dunn_severity_lst])
res_p_dunn_severity.index = q_kruskal_signif
res_q_dunn_severity = pd.concat([q.T for q in res_q_dunn_severity_lst])
res_q_dunn_severity.index = q_kruskal_signif

results_severity = pd.concat([meta_table["Gene Name"], n_per_group, r_df, p_u_mpvsCTRL, q_u_mpvsCTRL, p_kruskal_severity, q_kruskal_severity, contrasts_median_fc, res_p_dunn_severity, res_q_dunn_severity], axis=1)

results_severity["signif_MPvsCTRL"] = [True if x in results_severity[(results_severity["qfdr_u_MPvsCTRL"]<0.01) &  (~results_severity["MedFC_MPvsCTRL"].between(-0.20, 0.2))].index else False for x in results_severity.index]
results_severity["signif_severity"] = [True if x in results_severity[(results_severity["qfdr_kruskal_severity"]<0.05)].index else False for x in results_severity.index]
results_severity["signif_MPvsLLmf"] = [True if x in results_severity[(results_severity["qfdr_dunn_MPvsLLmf"]<0.05) ].index else False for x in results_severity.index]
results_severity["signif_MPvsLLew"] = [True if x in results_severity[(results_severity["qfdr_dunn_MPvsLLewmf"]<0.05) ].index else False for x in results_severity.index]
results_severity["signif_MPvsLLew"] = [True if x in results_severity[(results_severity["qfdr_dunn_MPvsLLew"]<0.05) ].index else False for x in results_severity.index]


results_severity.to_csv(
    os.path.join(res_path_mans, "diff_exp_analysis_mp.csv"), index=True
)
```


## Machine Learning

Classification of parasite Mansonella vs Loa

```{python}
# ---------------------
# 1. Load and filter data
# ---------------------

random_state=20250811

# only features with 100% completeness considered
missingness = df[meta_table.index].isna().mean()
low_missing_proteins = missingness[missingness <= 0.2].index
features_ml = list(set(low_missing_proteins) & set(meta_table.index))

# Filter only relevant classes
df_filtered = df[df['severity'].isin(['MP', 'LLmf'])].copy().dropna(subset="age") # 'LLewmf'

df_filtered.drop(df_filtered[(df_filtered["severity"]=="MP") & (df_filtered["age"].between(20, 40)) & (df_filtered["sex"]==0)].sample(20, random_state=45).index, inplace=True)
df_filtered.drop(df_filtered[(df_filtered["severity"]=="MP") & (df_filtered["sex"]==1)].sample(11, random_state=45).index, inplace=True)
df_filtered.drop(df_filtered[(df_filtered["severity"]=="MP") & (df_filtered["sex"]==0)].sample(12, random_state=45).index, inplace=True)


df_filtered_prot = df_filtered.rename(dict(zip(meta_table.index, meta_table["Gene Name"])), axis=1)

df_filtered_prot = pd.DataFrame(
    KNNImputer().fit_transform(df_filtered[features_ml]),
    index=df_filtered.index,
    columns=features_ml,
    )
df_filtered = pd.concat([df_filtered[["age", "sex", "severity",]] # "severity_combined"
, df_filtered_prot], axis=1)


# features_ml = feat_high_roc

# ---------------------
# 2. Hold out 14 samples for testing
# ---------------------
# Ensure stratification so class balance is maintained in test set
# Select 5 samples per class for the test set

test_df = (
    df_filtered.groupby('severity', group_keys=False)
    .apply(lambda x: resample(x, replace=False, n_samples=12, random_state=random_state))
)

# Remaining data is training set
train_df = df_filtered.drop(index=test_df.index)

# ---------------------
# 3. Balance sample sizes in training data
# ---------------------
min_count = train_df['severity'].value_counts().min()
balanced_train_df = (
    train_df.groupby('severity', group_keys=False)
    .apply(lambda x: resample(x, replace=False, n_samples=min_count, random_state=random_state))
)

res_roc = pd.DataFrame(index= features_ml, columns=["medFC", "AUROC"])
for p in features_ml:
    res_roc.loc[p, "medFC"] = train_df.loc[train_df["severity"]=="MP", p].median() - train_df.loc[train_df["severity"]=="LLmf", p].median()
    res_roc.loc[p, "AUROC"] = roc_auc_score(train_df["severity"], train_df[p])
res_roc.sort_index(inplace=True)
res_roc.sort_values("AUROC")

feat_high_roc = res_roc[(res_roc["AUROC"]<0.40) | (res_roc["AUROC"]>0.60)].index


print("Balanced training set severity counts:\n", balanced_train_df['severity'].value_counts())

# ---------------------
# 4. Define feature sets
# ---------------------
meta_cols = ['severity', 'sex']
protein_cols = feat_high_roc

y = balanced_train_df['severity']

X_sets = {
    "Proteins only": balanced_train_df[protein_cols],
    # "FBC": balanced_train_df[["lym_abs", "neu_abs", "mon_abs", "eos_abs", "bas_abs"]].dropna(),
    # "Age": balanced_train_df[["age"]],
    # "Sex": balanced_train_df[["sex"]],
    # "Proteins + FBC": balanced_train_df[
    #     list(protein_cols) + ["lym_abs", "neu_abs", "mon_abs", "eos_abs", "bas_abs"]].dropna(),
    # "Proteins + Sex": balanced_train_df[list(protein_cols) + ["sex"]],
    # "Proteins + Age": balanced_train_df[list(protein_cols) + ["age"]],
    # "Proteins + FBC + Sex": balanced_train_df[
    #     list(protein_cols) + ["lym_abs", "neu_abs", "mon_abs", "eos_abs", "bas_abs", "sex"]].dropna(),
    # "Proteins + FBC + Age": balanced_train_df[
        # list(protein_cols) + ["lym_abs", "neu_abs", "mon_abs", "eos_abs", "bas_abs", "age"]].dropna(),
    
    # "Proteins + FBC + Sex + Age": balanced_train_df[
    #     list(protein_cols) + ["lym_abs", "neu_abs", "mon_abs", "eos_abs", "bas_abs", "sex", "age"]].dropna(),
    # "Proteins + Sex + Age": balanced_train_df[list(protein_cols) + ["sex", "age"]],
    # "Sex + Age": balanced_train_df[["sex", "age"]],
}

# ---------------------
# 5. Define models
# ---------------------
scoring = ['accuracy', 'precision_macro', 'recall_macro', 'f1_macro', 'roc_auc']

cv = StratifiedKFold(n_splits=4, shuffle=True, random_state=random_state)
n_trees = 20
max_depth = 2

models = {
    "LogisticRegression": LogisticRegression(
        max_iter=500, penalty='elasticnet', solver='saga', l1_ratio=0.5, random_state=random_state),
    "RandomForest": RandomForestClassifier(
        random_state=random_state, max_depth=max_depth, n_estimators=n_trees),
    "GradientBoosting": GradientBoostingClassifier(
        random_state=random_state, max_depth=max_depth, n_estimators=n_trees), 
    "SVM": SVC(probability=True, kernel='rbf', random_state=random_state)
}

# Define different numbers of features to test
feature_counts = list(range(1, 36))


# Store learning curve results here
learning_curve_results = []

for set_name, X in X_sets.items():
    for model_name, model in models.items():
        for k in feature_counts:
            
            # Make sure k doesn't exceed number of features
            k_adjusted = min(k, X.shape[1])

            # Create pipeline with feature selection + classifier
            pipe = Pipeline([
                ('feature_selection', SelectKBest(score_func=f_classif, k=k_adjusted)),
                ('clf', clone(model))
            ])

            # Initialize variables
            best_params = {}
            scores = {}

            # No tuning for Logistic Regression or SVM
            scores = cross_validate(pipe, X, y.loc[X.index], cv=cv, scoring=scoring)

            avg_roc_auc = scores['test_roc_auc'].mean()
            avg_accuracy = scores["test_accuracy"].mean()

            learning_curve_results.append({
                'Feature_Set': set_name,
                'Model': model_name,
                'Num_Features': k_adjusted,
                'Mean_Accuracy': avg_accuracy,
            })

            if model_name=="RandomForest":
                if k==21:
                    break

lc_df = pd.DataFrame(learning_curve_results)
lc_df.to_csv(
    os.path.join(
        "results", "mansonella", "ml", "results_learning_curve.csv"
    )
)
# Plot learning curves
plt.figure(figsize=(12, 8))

for (set_name, model_name), group_df in lc_df.groupby(
    ['Feature_Set', 'Model']):
    plt.plot(
        group_df['Num_Features'], group_df['Mean_Accuracy'], marker='o', label=f"{set_name} - {model_name}") 

plt.xlabel("Number of Features Selected")
plt.ylabel("Mean Accuracy (cross-validated)")
plt.title("Learning Curve: Effect of Number of Selected Features on Accuracy")
plt.legend(loc='lower right')
plt.grid(True)
plt.tight_layout()
plt.savefig(
    os.path.join(
        "results", "mansonella", "ml", "learning_curve_cv_accuracy.png"
    )
)
plt.show()

```

```{python}

best_feature_set = "Proteins only"
best_model_name = "RandomForest"

print(f"\nEvaluating best model '{best_model_name}' with feature set '{best_feature_set}' on the test set...")

# Get the model object
best_model = models[best_model_name]

# Prepare training data
X_train_final = X_sets[best_feature_set]
y_train_final = y.loc[X_sets[best_feature_set].index]

# Prepare test data
test_features = test_df[list(X_train_final.columns)]
y_test = test_df['severity']

# Build and train pipeline

pipe_final = Pipeline([
    ('pipe_final', SelectKBest(score_func=f_classif, k=21)),
    ('clf', best_model)
])
  
pipe_final.fit(X_train_final, y_train_final)


# Predict on test set
y_pred = pipe_final.predict(test_features)
y_prob = pipe_final.predict_proba(test_features)[:, 1] if hasattr(pipe_final.named_steps['clf'], "predict_proba") else None

# Evaluation metrics
test_metrics = {
    'accuracy': accuracy_score(y_test, y_pred),
    'precision_macro': precision_score(y_test, y_pred, average='macro'),
    'recall_macro': recall_score(y_test, y_pred, average='macro'),
    'f1_macro': f1_score(y_test, y_pred, average='macro'),
}

if y_prob is not None:
    y_true_binary = (y_test == y_train_final.unique()[1]).astype(int)  # encode for binary AUC
    test_metrics['accuracy'] = roc_auc_score(y_true_binary, y_prob)

print("\nTest set performance:")
for metric, value in test_metrics.items():
    print(f"{metric}: {value:.3f}")

```

```{python}
selected_features = X_train_final.columns[pipe_final.named_steps['pipe_final'].get_support()]
fi = pipe_final.named_steps['clf'].feature_importances_

fi_df = pd.DataFrame(
    {
        "Genes": meta_table.loc[selected_features, "Gene Name"].values,
        "FI": fi,
    }, index=selected_features
).sort_values(by="FI")[::-1]

fi_df = fi_df.iloc[:15]
```

```{python}


# ---------------------
# 11. ROC Curve: Train (CV) and Test
# ---------------------

# Re-map labels to binary for ROC
label_mapping = {label: idx for idx, label in enumerate(np.unique(y_train_final))}
y_train_bin = y_train_final.map(label_mapping).values
y_test_bin = y_test.map(label_mapping).values

# 1. ROC Curve on Training Set (CV predictions)
y_train_proba_cv = cross_val_predict(
    pipe_final, X_train_final, y_train_final,
    cv=cv, method='predict_proba'
)[:, 1]

fpr_train, tpr_train, _ = roc_curve(y_train_bin, y_train_proba_cv)
roc_auc_train = auc(fpr_train, tpr_train)

# 2. ROC Curve on Test Set
y_test_proba = pipe_final.predict_proba(test_features)[:, 1]
fpr_test, tpr_test, _ = roc_curve(y_test_bin, y_test_proba)
roc_auc_test = auc(fpr_test, tpr_test)


# Test set predictions at threshold 0.5
y_test_pred = (y_test_proba >= 0.5).astype(int)
cm_test = pd.DataFrame(
    confusion_matrix(y_test_bin, y_test_pred), 
    index=["LLmf", "MP"], columns=["LLmf", "MP"])

y_train_pred_cv = (y_train_proba_cv >= 0.5).astype(int)
cm_train = pd.DataFrame(
    confusion_matrix(y_train_bin, y_train_pred_cv),
    index=["LLmf", "MP"], columns=["LLmf", "MP"])



fig, axs = plt.subplots(1, 2, figsize=(6,3.5))

sns.heatmap(
    ax=axs[0], data=cm_train, annot=True, 
    cmap=sns.color_palette("Oranges"), cbar=False, 
    linewidths=1, linecolor='black')
sns.heatmap(
    ax=axs[1], data=cm_test, annot=True, 
    cmap=sns.color_palette("Oranges"), cbar=False, 
    linewidths=1, linecolor='black')

axs[0].set_title("Train/Validation")
axs[1].set_title("Test")

for ax in axs:
    ax.spines['left'].set_linewidth(2)  # Left border thickness
    ax.spines['bottom'].set_linewidth(2) # Bottom border thickness
    ax.spines['right'].set_linewidth(2) # Bottom border thickness
    ax.spines['top'].set_linewidth(2) # Bottom border thickness

axs[0].spines['left'].set_linewidth(2)
fig.supxlabel("True Groups")
fig.supylabel("Predicted Groups")
plt.tight_layout()
plt.savefig(
    os.path.join("results", "mansonella", "ml", "cm_rf_MPvsLLMF.png"), dpi=600)

```


## Figures


Volcano LN vs MP
```{python}
results_severity_plotting = results_severity.copy()
for col in [c for c in results_severity_plotting.columns if "p_u" in c]:
    results_severity_plotting["negLog10_" + col] = -np.log10(results_severity_plotting[col])
for col in [c for c in results_severity_plotting.columns if "qfdr_u" in c]:
    results_severity_plotting["negLog10_" + col] = -np.log10(results_severity_plotting[col])

#negLog10_qfdr_u_MPvsCTRL
#negLog10_p_u_MPvsCTRL

p_vals = "negLog10_p_u_MPvsCTRL"
p_vals = "negLog10_qfdr_u_MPvsCTRL"

fig, ax = plt.subplots(1,1, figsize=(5,5))


signif = results_severity_plotting[(~results_severity_plotting[f"MedFC_MPvsCTRL"].between(-0.2, 0.2)) & (results_severity_plotting[p_vals]>2)].index

sns.scatterplot(
    ax=ax, alpha=0.5,
    data = results_severity_plotting.drop(signif), c="gray",
    x=f"MedFC_MPvsCTRL", y=p_vals
)
sns.scatterplot(
    ax=ax, alpha=0.5,
    data = results_severity_plotting.loc[signif], c=sns.color_palette("colorblind")[3],
    x=f"MedFC_MPvsCTRL", y=p_vals
)

features_annot = results_severity_plotting[(~results_severity_plotting[f"MedFC_MPvsCTRL"].between(-0.2, 0.2)) & (results_severity_plotting[p_vals]>2)].index
for f in features_annot:
    ax.text(
        x=results_severity_plotting[f"MedFC_MPvsCTRL"].loc[f],
        y=results_severity_plotting[p_vals].loc[f],
        s=meta_table.loc[f, "Gene Name"]
    )

ax.spines['left'].set_linewidth(2)  # Left border thickness
ax.spines['bottom'].set_linewidth(2) # Bottom border thickness
ax.spines['right'].set_linewidth(2) # Bottom border thickness
ax.spines['top'].set_linewidth(2) # Bottom border thickness
    # Set y-axis ticks to one decimal place
ax.yaxis.set_major_formatter(ticker.FormatStrFormatter('%.1f'))
plt.tick_params(axis='both', which='major', width=3)  # Adjust width of major ticks
plt.tick_params(axis='both', which='minor', width=3)  # Adjust width of minor ticks

# ax.set_title(c)
ax.set_xlabel("Median $ Log_{2} FC$")
ax.set_ylabel("$-log_{10} (q_{u})$")
ax.set_title("MP vs. CTRL")

ax.axhline(2, ls="--", c="gray")
# ax.axvline(0, ls="--", c="gray")
ax.axvline(-.2, ls="--", c="gray")
ax.axvline(.2, ls="--", c="gray")
plt.tight_layout()
plt.savefig(
    os.path.join("results", "mansonella", "plots", "volcano", 'MPvsCTRL.png'), dpi=600)
plt.show()
```


Boxplots per proteins
```{python}
colors_severity_mans = {
    "CTRL": sns.color_palette("colorblind")[0],
    "MP": sns.color_palette("colorblind")[3],
    "LLmf": sns.color_palette("colorblind")[1],
    "LLewmf": sns.color_palette("colorblind")[2],
    "LLew": sns.color_palette("colorblind")[4],
    
}
target_severity_mans = "severity"
order_severity_mans = groups_severity_mans
order_severity_mans_label = ['CTRL', 'MP', 'LL\nmf', 'LL\newmf', 'LL\new']

for p in list(meta_table.index):    

    fig, ax = plt.subplots(1,1, figsize=(3,3))
    sns.boxplot(
        data=data_mans, 
        x=target_severity_mans, y=p, order=order_severity_mans,
        fliersize=0, fill=False, color="k",
        legend=False,
        capprops = dict(linewidth=1.5),
        boxprops = dict(linewidth=1.5), medianprops = dict(linewidth=3, color="k"), 
        whiskerprops = dict(linestyle='--', color='black', linewidth=1.5))
    sns.stripplot(
        data=data_mans, x=target_severity_mans, y=p, 
        order=order_severity_mans, hue=target_severity_mans, alpha=0.3, 
        palette=list(colors_severity_mans.values()), hue_order=order_severity_mans, 
        edgecolor=list(colors_severity_mans.values()))

    ax.set_ylabel(f"$Log_2$ abundance {meta_table.loc[p, 'Gene Name']}")
    ax.set_xlabel(f"", fontweight="bold")
    ax.set_yticklabels(ax.get_yticklabels())
    ax.set_xticklabels(order_severity_mans_label, rotation=0)
    ax.axvline(0.5, ls="--", c="k")

    ax.spines['left'].set_linewidth(2)  # Left border thickness
    ax.spines['bottom'].set_linewidth(2) # Bottom border thickness
    ax.spines['right'].set_linewidth(2) # Bottom border thickness
    ax.spines['top'].set_linewidth(2) # Bottom border thickness
    # Set y-axis ticks to one decimal place
    ax.yaxis.set_major_formatter(ticker.FormatStrFormatter('%.1f'))
    

    ax.set_title("$q_{kruskal, infected}$: "+  f"{results_severity.loc[p, 'q_kruskal_severity']:.2e}", fontsize=11)
    plt.tick_params(axis='both', which='major', width=3)  # Adjust width of major ticks
    plt.tick_params(axis='both', which='minor', width=3)  # Adjust width of minor ticks
    plt.tight_layout()
    plt.savefig(
        os.path.join("results", "mansonella", "plots", "boxplots", "severity", f"{meta_table.loc[p, 'Gene Name']}_{p}_{'signif' if results_severity.loc[p, 'q_kruskal_severity']<0.05 else ''}.png"), dpi=600)
    plt.close()
    # break
```


```{python}
# Most important feature barplot
fig, ax = plt.subplots(1,1, figsize=(3,5))
sns.barplot(fi_df.set_index("Genes")["FI"], orient="h", palette=sns.color_palette("Oranges", n_colors=15)[::-1])

ax.set_ylabel(f"Proteins")
ax.set_xlabel(f"Feature Importance RF")

ax.spines['left'].set_linewidth(2)  # Left border thickness
ax.spines['bottom'].set_linewidth(2) # Bottom border thickness
ax.spines['right'].set_linewidth(2) # Bottom border thickness
ax.spines['top'].set_linewidth(2) # Bottom border thickness

plt.tick_params(axis='both', which='major', width=3)  # Adjust width of major ticks
plt.tick_params(axis='both', which='minor', width=3)  # Adjust width of minor ticks
plt.tight_layout()
plt.savefig(
    os.path.join("results", "mansonella", "ml", "fi_rf_MPvsLLMF.png"), dpi=600)
```


```{python}
# ROC Curve - MP vs llmf
fig, ax = plt.subplots(1,1, figsize=(5,5))
ax.plot(fpr_train, tpr_train, label=f'Training ROC (AUC = {roc_auc_train:.2f})', color=sns.color_palette("colorblind")[3], linestyle='-.', lw=4, alpha=0.5)
ax.plot(fpr_test, tpr_test, label=f'Test ROC (AUC = {roc_auc_test:.2f})', color=sns.color_palette("colorblind")[3], lw=4)
ax.plot([0, 1], [0, 1], 'k--')
ax.set_ylabel(f"TPR (Sensitivity)")
ax.set_xlabel(f"FPR (1 - Specificity)")

ax.spines['left'].set_linewidth(2)  # Left border thickness
ax.spines['bottom'].set_linewidth(2) # Bottom border thickness
ax.spines['right'].set_linewidth(2) # Bottom border thickness
ax.spines['top'].set_linewidth(2) # Bottom border thickness

plt.legend(loc='upper left')

plt.grid(True)

plt.tick_params(axis='both', which='major', width=3)  # Adjust width of major ticks
plt.tick_params(axis='both', which='minor', width=3)  # Adjust width of minor ticks
plt.tight_layout()
plt.savefig(
    os.path.join("results", "mansonella", "ml", "ROC_rf_MPvsLLMF.png"), dpi=600)
```

```{python}
# Barplots for accuracy
fig, ax = plt.subplots(1,1, figsize=(2,2.5), facecolor=(1, 1, 1, 0.0))
sns.barplot(
    pd.Series([0.7417582417582417 ,test_metrics["accuracy"]], index=["Train/Val", "Test"]), 
    orient="v", palette=sns.color_palette("Oranges", n_colors=2),
    edgecolor="gray")

ax.set_ylabel(f"Accuracy (%)")

ax.spines['left'].set_linewidth(2)  # Left border thickness
ax.spines['bottom'].set_linewidth(2) # Bottom border thickness
ax.spines['right'].set_linewidth(2) # Bottom border thickness
ax.spines['top'].set_linewidth(2) # Bottom border thickness

# ax.set_yticks([0.5, 0.6, 0.7])
ax.set_ylim([0.5, 0.79])
ax.text(-0.3, 0.75, "0.74")
ax.text(0.7, test_metrics["accuracy"]+0.01, np.round(test_metrics["accuracy"], 2))
plt.tick_params(axis='both', which='major', width=3)  # Adjust width of major ticks
plt.tick_params(axis='both', which='minor', width=3)  # Adjust width of minor ticks

plt.tight_layout()
plt.savefig(
    os.path.join("results", "mansonella", "ml", "acc_bar_rf_MPvsLLMF.png"), dpi=600)
```

```{python}
# Boxplots for MP vs LLmf for most important features
for i, p in enumerate(fi_df.index):
    fig, ax = plt.subplots(1,1, figsize=(1.7,2.5))
    sns.boxplot(
        data=df_filtered, 
        x="severity", y=p, order=["MP", "LLmf"],
        fliersize=0, fill=False, color="k",
        legend=False,
        capprops = dict(linewidth=1.5),
        boxprops = dict(linewidth=1.5), medianprops = dict(linewidth=3, color="k"), 
        whiskerprops = dict(linestyle='--', color='black', linewidth=1.5))
    sns.stripplot(
        data=data_mans, x="severity", y=p, 
        order=["MP", "LLmf"], alpha=0.3, 
        palette=[
            sns.color_palette("colorblind")[3],
            sns.color_palette("colorblind")[1]]
        )

    ax.set_ylabel(f"$Log_2$ abundance {meta_table.loc[p, 'Gene Name']}")
    ax.set_xlabel(f"", fontweight="bold")
    ax.set_yticklabels(ax.get_yticklabels())
    ax.set_xticklabels(["MP", "LLmf"], rotation=0)
    ax.spines['left'].set_linewidth(2)  # Left border thickness
    ax.spines['bottom'].set_linewidth(2) # Bottom border thickness
    ax.spines['right'].set_linewidth(2) # Bottom border thickness
    ax.spines['top'].set_linewidth(2) # Bottom border thickness
    # Set y-axis ticks to one decimal place
    ax.yaxis.set_major_formatter(ticker.FormatStrFormatter('%.1f'))

    plt.tick_params(axis='both', which='major', width=3)  # Adjust width of major ticks
    plt.tick_params(axis='both', which='minor', width=3)  # Adjust width of minor ticks
    plt.tight_layout()
    plt.savefig(
        os.path.join("results", "mansonella", "ml", "boxplots", f"top{i+1}_{meta_table.loc[p, 'Gene Name']}_{p}.png"), dpi=600)
    plt.close()
```

```{python}
# Correlation with mp mf
df["log2_mp_mf"] = np.log2(df["mp_mf"]+1)
df_mf = df[df["mp_mf"]>0]

for p in list(results_severity["r_srho_mpmf"].sort_values().head(5).index) +list(results_severity["r_srho_mpmf"].sort_values().tail(5).index):
    p_gene = meta_table.loc[p, "Gene Name"]

    fig, ax = plt.subplots(1,1, figsize=(3,3))
    sns.scatterplot(
        data=df_mf, 
        y="log2_mp_mf", x=p,
        color=sns.color_palette("colorblind")[3], alpha=0.6,
        legend=False)
    
    

    ax.set_xlabel(f"$Log_2$ abundance {p_gene}")
    ax.set_ylabel(f"$Log_2$ parasites per µL")
    # ax.spines[['right', 'top']].set_visible(False)
    ax.spines['left'].set_linewidth(2)  # Left border thickness
    ax.spines['bottom'].set_linewidth(2) # Bottom border thickness
    ax.spines['right'].set_linewidth(2) # Bottom border thickness
    ax.spines['top'].set_linewidth(2) # Bottom border thickness
    # Set y-axis ticks to one decimal place
    ax.yaxis.set_major_formatter(ticker.FormatStrFormatter('%.1f'))
    ax.set_title("r: "+  f"{results_severity.loc[p, 'r_srho_mpmf']:.2f}, "+"q: "+  f"{results_severity.loc[p, 'p_srho_mpmf']:.2e}", fontsize=11)
    plt.tick_params(axis='both', which='major', width=3)  # Adjust width of major ticks
    plt.tick_params(axis='both', which='minor', width=3)  # Adjust width of minor ticks
    plt.tight_layout()
    
    plt.savefig(
        os.path.join("results", "mansonella", "plots", "parasite_count",  f'{results_severity.loc[p, "r_srho_mpmf"]:.2f}_para{p_gene}.png'), dpi=600)
    # break
    plt.close()
    # print(p)
```


```{python}
# sns.scatterplot(df_mf, x="log2_mp_mf", y="age", hue=feat)

for p in ["IGHM", "CD5L", "IGHG3"]:

    feat = meta_table[meta_table["Gene Name"]==p].index.values[0]
    order = ["CTRL", "MP"]
    palette = [sns.color_palette("colorblind")[0], sns.color_palette("colorblind")[1]]

    df_plot = df[(df["severity"]=="CTRL") | ((df["severity"]=="MP") & (df["mp_mf"]>0))]
    
    s_rho_mp,_ = spearmanr(
        df_plot[df_plot["severity"]=="MP"][feat],
        df_plot[df_plot["severity"]=="MP"]["age"], nan_policy="omit"
    )
    s_rho_ctrl,_ = spearmanr(
        df_plot[df_plot["severity"]=="CTRL"][feat],
        df_plot[df_plot["severity"]=="CTRL"]["age"], nan_policy="omit"
    )

    fig, ax = plt.subplots(1,1, figsize=(4,4))
    sns.regplot(
        ax=ax,
        data=df_plot[df_plot["severity"]=="CTRL"], x=feat, y="age", 
        color=palette[0], label="$r_{CTRL}$ "+ f"= {s_rho_ctrl:.2f}",
        )
    sns.regplot(
        ax=ax,
        data=df_plot[df_plot["severity"]=="MP"], x=feat, y="age", 
        color=palette[1], label="$r_{MP}$ "+ f"= {s_rho_mp:.2f}"
        )
    ax.set_xlabel(f"$Log_2$ abundance {p}")
    ax.set_ylabel(f"Age in years")
    # ax.spines[['right', 'top']].set_visible(False)
    ax.spines['left'].set_linewidth(2)  # Left border thickness
    ax.spines['bottom'].set_linewidth(2) # Bottom border thickness
    ax.spines['right'].set_linewidth(2) # Bottom border thickness
    ax.spines['top'].set_linewidth(2) # Bottom border thickness
    plt.legend()
    plt.tight_layout()
    plt.savefig(
    os.path.join("results", "mansonella", "plots", "age_proteins",  f'{p}.png'), dpi=600)

```


## Coinfections

```{python}

groups_severity_mans_co = [
 'CTRL', 'MP', 'LLmf', 'LLewmf', 'LLew',
 'LLmf_MP', 'LLewmf_MP', 'LLew_MP',
 ]

df_co = data_mans[data_mans["severity"].isin(groups_severity_mans_co)]

df_co.groupby("severity")["age"].median() # age seems noch signficantly different
# df_co.groupby("severity")["sex"].value_counts(normalize=True) # sex seems noch signficantly different


contrasts = [
    ("LLmf", "LLmf_MP"),
    ("LLewmf", "LLewmf_MP"),
    ("LLew", "LLew_MP"),
]
```